<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Open Principles of Microeconomics - 8.2 How Perfectly Competitive Firms Make Output Decisions</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./8-3-entry-and-exit-decisions-in-the-long-run.html" rel="next">
<link href="./8-1-perfect-competition-and-why-it-matters.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./8-introduction-to-perfect-competition.html">8-Perfect Competition</a></li><li class="breadcrumb-item"><a href="./8-2-how-perfectly-competitive-firms-make-output-decisions.html"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">8.2 How Perfectly Competitive Firms Make Output Decisions</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Open Principles of Microeconomics</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">1-Welcome to Economics!</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1-introduction.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter Objectives</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1-1-what-is-economics-and-why-is-it-important.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">1.1 What Is Economics, and Why Is It Important?</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1-2-microeconomics-and-macroeconomics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">1.2 Microeconomics and Macroeconomics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1-3-how-economists-use-theories-and-models-to-understand-economic-issues.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">1.3 How Economists Use Theories and Models to Understand Economic Issues</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1-4-how-to-organize-economies-an-overview-of-economic-systems.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">1.4 How To Organize Economies: An Overview of Economic Systems</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">2-Choice in a World of Scarcity</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2-introduction-to-choice-in-a-world-of-scarcity.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter Objectives</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2-1-how-individuals-make-choices-based-on-their-budget-constraint.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">2.1 How Individuals Make Choices Based on Their Budget Constraint</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2-2-the-production-possibilities-frontier-and-social-choices.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">2.2 The Production Possibilities Frontier and Social Choices</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2-3-confronting-objections-to-the-economic-approach.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">2.3 Confronting Objections to the Economic Approach</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
 <span class="menu-text">3-Demand and Supply</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./3-introduction-to-demand-and-supply.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter Objectives</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./3-1-demand-supply-and-equilibrium-in-markets-for-goods-and-services.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">3.1 Demand, Supply, and Equilibrium in Markets for Goods and Services</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./3-2-shifts-in-demand-and-supply-for-goods-and-services.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">3.2 Shifts in Demand and Supply for Goods and Services</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./3-3-changes-in-equilibrium-price-and-quantity-the-four-step-process.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">3.3 Changes in Equilibrium Price and Quantity: The Four-Step Process</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./3-4-price-ceilings-and-price-floors.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">3.4 Price Ceilings and Price Floors</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./3-5-demand-supply-and-efficiency.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">3.5 Demand, Supply, and Efficiency</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
 <span class="menu-text">4-Labor and Financial Markets</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./4-introduction-to-labor-and-financial-markets.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter Objectives</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./4-1-demand-and-supply-at-work-in-labor-markets.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">4.1 Demand and Supply at Work in Labor Markets</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./4-2-demand-and-supply-in-financial-markets.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">4.2 Demand and Supply in Financial Markets</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./4-3-the-market-system-as-an-efficient-mechanism-for-information.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">4.3 The Market System as an Efficient Mechanism for Information</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
 <span class="menu-text">5-Elasticity</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./5-introduction-to-elasticity.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter Objectives</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./5-1-price-elasticity-of-demand-and-price-elasticity-of-supply.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">5.1 Price Elasticity of Demand and Price Elasticity of Supply</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./5-2-polar-cases-of-elasticity-and-constant-elasticity.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">5.2 Polar Cases of Elasticity and Constant Elasticity</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./5-3-elasticity-and-pricing.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">5.3 Elasticity and Pricing</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./5-4-elasticity-in-areas-other-than-price.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">5.4 Elasticity in Areas Other Than Price</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">
 <span class="menu-text">6-Consumer Choices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./6-introduction-to-consumer-choices.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter Objectives</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./6-1-consumption-choices.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">6.1 Consumption Choices</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./6-2-how-changes-in-income-and-prices-affect-consumption-choices.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">6.2 How Changes in Income and Prices Affect Consumption Choices</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./6-3-behavioral-economics-an-alternative-framework-for-consumer-choice.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">6.3 Behavioral Economics: An Alternative Framework for Consumer Choice</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true">
 <span class="menu-text">7-Production, Costs, and Industry Structure</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./7-introduction-to-production-costs-and-industry-structure.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter Objectives</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./7-1-explicit-and-implicit-costs-and-accounting-and-economic-profit.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">7.1 Explicit and Implicit Costs, and Accounting and Economic Profit</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./7-2-production-in-the-short-run.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">7.2 Production in the Short Run</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./7-3-costs-in-the-short-run.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">7.3 Costs in the Short Run</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./7-4-production-in-the-long-run.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">7.4 Production in the Long Run</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./7-5-costs-in-the-long-run.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">7.5 Costs in the Long Run</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="true">
 <span class="menu-text">8-Perfect Competition</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./8-introduction-to-perfect-competition.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter Objectives</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./8-1-perfect-competition-and-why-it-matters.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">8.1 Perfect Competition and Why It Matters</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./8-2-how-perfectly-competitive-firms-make-output-decisions.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">8.2 How Perfectly Competitive Firms Make Output Decisions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./8-3-entry-and-exit-decisions-in-the-long-run.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">8.3 Entry and Exit Decisions in the Long Run</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./8-4-efficiency-in-perfectly-competitive-markets.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">8.4 Efficiency in Perfectly Competitive Markets</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="true">
 <span class="menu-text">9-Monopoly</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./9-introduction-to-a-monopoly.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter Objectives</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./9-1-how-monopolies-form-barriers-to-entry.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">9.1 How Monopolies Form: Barriers to Entry</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./9-2-how-a-profit-maximizing-monopoly-chooses-output-and-price.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">9.2 How a Profit-Maximizing Monopoly Chooses Output and Price</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" aria-expanded="true">
 <span class="menu-text">10-Monopolistic Competition and Oligopoly</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-introduction-to-monopolistic-competition-and-oligopoly.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter Objectives</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-1-monopolistic-competition.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">10.1 Monopolistic Competition</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-2-oligopoly.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">10.2 Oligopoly</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" aria-expanded="true">
 <span class="menu-text">11-Monopoly and Antitrust Policy</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-introduction-to-monopoly-and-antitrust-policy.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter Objectives</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-1-corporate-mergers.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">11.1 Corporate Mergers</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-2-regulating-anticompetitive-behavior.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">11.2 Regulating Anticompetitive Behavior</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-3-regulating-natural-monopolies.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">11.3 Regulating Natural Monopolies</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-4-the-great-deregulation-experiment.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">11.4 The Great Deregulation Experiment</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" aria-expanded="true">
 <span class="menu-text">12-Environmental Protection and Negative Externalities</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-12" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-introduction-to-environmental-protection-and-negative-externalities.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter Objectives</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-1-the-economics-of-pollution.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">12.1 The Economics of Pollution</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-2-command-and-control-regulation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">12.2 Command-and-Control Regulation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-3-market-oriented-environmental-tools.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">12.3 Market-Oriented Environmental Tools</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-4-the-benefits-and-costs-of-u-s-environmental-laws.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">12.4 The Benefits and Costs of U.S. Environmental Laws</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-5-international-environmental-issues.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">12.5 International Environmental Issues</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-6-the-tradeoff-between-economic-output-and-environmental-protection.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">12.6 The Tradeoff between Economic Output and Environmental Protection</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" aria-expanded="true">
 <span class="menu-text">13-Positive Externalities and Public Goods</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-13" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-introduction-to-positive-externalities-and-public-goods.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter Objectives</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-1-investments-in-innovation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">13.1 Investments in Innovation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-2-how-governments-can-encourage-innovation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">13.2 How Governments Can Encourage Innovation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-3-public-goods.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">13.3 Public Goods</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" aria-expanded="true">
 <span class="menu-text">14-Labor Markets and Income</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-14" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-introduction-to-labor-markets-and-income.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter Objectives</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-1-the-theory-of-labor-markets.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">14.1 The Theory of Labor Markets</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-2-wages-and-employment-in-an-imperfectly-competitive-labor-market.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">14.2 Wages and Employment in an Imperfectly Competitive Labor Market</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-3-market-power-on-the-supply-side-of-labor-markets-unions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">14.3 Market Power on the Supply Side of Labor Markets: Unions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-4-bilateral-monopoly.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">14.4 Bilateral Monopoly</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-5-employment-discrimination.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">14.5 Employment Discrimination</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-6-immigration.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">14.6 Immigration</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-15" aria-expanded="true">
 <span class="menu-text">15-Poverty and Economic Inequality</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-15" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-15" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-introduction-to-poverty-and-economic-inequality.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter Objectives</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-1-drawing-the-poverty-line.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">15.1 Drawing the Poverty Line</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-2-the-poverty-trap.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">15.2 The Poverty Trap</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-3-the-safety-net.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">15.3 The Safety Net</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-4-income-inequality-measurement-and-causes.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">15.4 Income Inequality: Measurement and Causes</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-5-government-policies-to-reduce-income-inequality.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">15.5 Government Policies to Reduce Income Inequality</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-16" aria-expanded="true">
 <span class="menu-text">16-Information, Risk, and Insurance</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-16" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-16" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-introduction-to-information-risk-and-insurance.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter Objectives</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-1-the-problem-of-imperfect-information-and-asymmetric-information.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">16.1 The Problem of Imperfect Information and Asymmetric Information</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-2-insurance-and-imperfect-information.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">16.2 Insurance and Imperfect Information</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-17" aria-expanded="true">
 <span class="menu-text">17-Financial Markets</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-17" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-17" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17-introduction-to-financial-markets.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter Objectives</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17-1-how-businesses-raise-financial-capital.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">17.1 How Businesses Raise Financial Capital</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17-2-how-households-supply-financial-capital.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">17.2 How Households Supply Financial Capital</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17-3-how-to-accumulate-personal-wealth.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">17.3 How to Accumulate Personal Wealth</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-18" aria-expanded="true">
 <span class="menu-text">18-Public Economy</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-18" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-18" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./18-introduction-to-public-economy.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter Objectives</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./18-1-voter-participation-and-costs-of-elections.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">18.1 Voter Participation and Costs of Elections</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./18-2-special-interest-politics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">18.2 Special Interest Politics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./18-3-flaws-in-the-democratic-system-of-government.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">18.3 Flaws in the Democratic System of Government</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-19" aria-expanded="true">
 <span class="menu-text">19-International Trade</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-19" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-19" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./19-introduction-to-international-trade.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter Objectives</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./19-1-absolute-and-comparative-advantage.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">19.1 Absolute and Comparative Advantage</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./19-2-what-happens-when-a-country-has-an-absolute-advantage-in-all-goods.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">19.2 What Happens When a Country Has an Absolute Advantage in All Goods</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./19-3-intra-industry-trade-between-similar-economies.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">19.3 Intra-industry Trade between Similar Economies</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./19-4-the-benefits-of-reducing-barriers-to-international-trade.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">19.4 The Benefits of Reducing Barriers to International Trade</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-20" aria-expanded="true">
 <span class="menu-text">20-Globalization and Protectionism</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-20" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-20" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./20-introduction-to-globalization-and-protectionism.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter Objectives</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./20-1-protectionism-an-indirect-subsidy-from-consumers-to-producers.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">20.1 Protectionism: An Indirect Subsidy from Consumers to Producers</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./20-2-international-trade-and-its-effects-on-jobs-wages-and-working-conditions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">20.2 International Trade and Its Effects on Jobs, Wages, and Working Conditions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./20-3-arguments-in-support-of-restricting-imports.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">20.3 Arguments in Support of Restricting Imports</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./20-4-how-governments-enact-trade-policy-globally-regionally-and-nationally.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">20.4 How Governments Enact Trade Policy: Globally, Regionally, and Nationally</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./20-5-the-tradeoffs-of-trade-policy.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">20.5 The Tradeoffs of Trade Policy</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#learning-objectives" id="toc-learning-objectives" class="nav-link active" data-scroll-target="#learning-objectives">Learning Objectives</a></li>
  <li><a href="#determining-the-highest-profit-by-comparing-total-revenue-and-total-cost" id="toc-determining-the-highest-profit-by-comparing-total-revenue-and-total-cost" class="nav-link" data-scroll-target="#determining-the-highest-profit-by-comparing-total-revenue-and-total-cost">Determining the Highest Profit by Comparing Total Revenue and Total Cost</a></li>
  <li><a href="#comparing-marginal-revenue-and-marginal-costs" id="toc-comparing-marginal-revenue-and-marginal-costs" class="nav-link" data-scroll-target="#comparing-marginal-revenue-and-marginal-costs">Comparing Marginal Revenue and Marginal Costs</a></li>
  <li><a href="#work-it-out" id="toc-work-it-out" class="nav-link" data-scroll-target="#work-it-out">Work It Out</a></li>
  <li><a href="#profits-and-losses-with-the-average-cost-curve" id="toc-profits-and-losses-with-the-average-cost-curve" class="nav-link" data-scroll-target="#profits-and-losses-with-the-average-cost-curve">Profits and Losses with the Average Cost Curve</a></li>
  <li><a href="#clear-it-up" id="toc-clear-it-up" class="nav-link" data-scroll-target="#clear-it-up">Clear It Up</a></li>
  <li><a href="#the-shutdown-point" id="toc-the-shutdown-point" class="nav-link" data-scroll-target="#the-shutdown-point">The Shutdown Point</a></li>
  <li><a href="#short-run-outcomes-for-perfectly-competitive-firms" id="toc-short-run-outcomes-for-perfectly-competitive-firms" class="nav-link" data-scroll-target="#short-run-outcomes-for-perfectly-competitive-firms">Short-Run Outcomes for Perfectly Competitive Firms</a></li>
  <li><a href="#marginal-cost-and-the-firms-supply-curve" id="toc-marginal-cost-and-the-firms-supply-curve" class="nav-link" data-scroll-target="#marginal-cost-and-the-firms-supply-curve">Marginal Cost and the Firm’s Supply Curve</a></li>
  <li><a href="#link-it-up" id="toc-link-it-up" class="nav-link" data-scroll-target="#link-it-up">Link It Up</a></li>
  <li><a href="#work-it-out-1" id="toc-work-it-out-1" class="nav-link" data-scroll-target="#work-it-out-1">Work It Out</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">8.2 How Perfectly Competitive Firms Make Output Decisions</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="learning-objectives" class="level3">
<h3 class="anchored" data-anchor-id="learning-objectives">Learning Objectives</h3>
<p>By the end of this section, you will be able to:</p>
<ul>
<li>Calculate profits by comparing total revenue and total cost</li>
<li>Identify profits and losses with the average cost curve</li>
<li>Explain the shutdown point</li>
<li>Determine the price at which a firm should continue producing in the short run</li>
</ul>
<p>A perfectly competitive firm has only one major decision to make—namely, what quantity to produce. To understand this, consider a different way of writing out the basic definition of profit:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="media/rId24.png" style="width:5.15625in;height:0.39583in" class="figure-img"></p>
<figcaption class="figure-caption">multiline equation line 1 Profit equals Total revenue minus Total cost line 2 equals left parenthesis Price right parenthesis times left parenthesis Quantity produced right parenthesis minus left parenthesis Average cost right parenthesis times left parenthesis Quantity produced right parenthesis</figcaption>
</figure>
</div>
<p>Since a perfectly competitive firm must accept the price for its output as determined by the product’s market demand and supply, it cannot choose the price it charges. This is already determined in the profit equation, and so the perfectly competitive firm can sell any number of units at exactly the same price. It implies that the firm faces a perfectly elastic demand curve for its product: buyers are willing to buy any number of units of output from the firm at the market price. When the perfectly competitive firm chooses what quantity to produce, then this quantity—along with the prices prevailing in the market for output and inputs—will determine the firm’s total revenue, total costs, and ultimately, level of profits.</p>
</section>
<section id="determining-the-highest-profit-by-comparing-total-revenue-and-total-cost" class="level3">
<h3 class="anchored" data-anchor-id="determining-the-highest-profit-by-comparing-total-revenue-and-total-cost">Determining the Highest Profit by Comparing Total Revenue and Total Cost</h3>
<p>A perfectly competitive firm can sell as large a quantity as it wishes, as long as it accepts the prevailing market price. The formula above shows that total revenue depends on the quantity sold and the price charged. If the firm sells a higher quantity of output, then total revenue will increase. If the market price of the product increases, then total revenue also increases whatever the quantity of output sold. As an example of how a perfectly competitive firm decides what quantity to produce, consider the case of a small farmer who produces raspberries and sells them frozen for $4 per pack. Sales of one pack of raspberries will bring in $4, two packs will be $8, three packs will be $12, and so on. If, for example, the price of frozen raspberries doubles to $8 per pack, then sales of one pack of raspberries will be $8, two packs will be $16, three packs will be $24, and so on.</p>
<p><a href="#ch08mod02_tab01">Table 8.1</a> shows total revenue and total costs for the raspberry farm; these data also appear in <a href="#CNX_Econ_C08_001">Figure 8.2</a>. The horizontal axis shows the quantity of frozen raspberries produced in packs. The vertical axis shows both total revenue and total costs, measured in dollars. The total cost curve intersects with the vertical axis at a value that shows the level of fixed costs, and then slopes upward. All these cost curves follow the same characteristics as the curves that we covered in the <a href="http://openstax.org/books/principles-microeconomics-3e/pages/7-introduction-to-production-costs-and-industry-structure">Production, Costs and Industry Structure</a> chapter.</p>
<p><img src="media/8-2-how-perfectly-competitive-firms-make-output-decisions_rId29.jpeg" style="width:4.88in;height:2.435in"></p>
<p>Figure 8.2 Total Cost and Total Revenue at the Raspberry Farm Total revenue for a perfectly competitive firm is a straight line sloping up. The slope is equal to the price of the good. Total cost also slopes up, but with some curvature. At higher levels of output, total cost begins to slope upward more steeply because of diminishing marginal returns. The maximum profit will occur at the quantity where the difference between total revenue and total cost is largest.</p>
<table class="table">
<colgroup>
<col style="width: 24%">
<col style="width: 24%">
<col style="width: 24%">
<col style="width: 24%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Quantity<br>
(Q)</th>
<th style="text-align: left;">Total Cost<br>
(TC)</th>
<th style="text-align: left;">Total Revenue<br>
(TR)</th>
<th style="text-align: left;">Profit</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">0</td>
<td style="text-align: left;">$62</td>
<td style="text-align: left;">$0</td>
<td style="text-align: left;">−$62</td>
</tr>
<tr class="even">
<td style="text-align: left;">10</td>
<td style="text-align: left;">$90</td>
<td style="text-align: left;">$40</td>
<td style="text-align: left;">−$50</td>
</tr>
<tr class="odd">
<td style="text-align: left;">20</td>
<td style="text-align: left;">$110</td>
<td style="text-align: left;">$80</td>
<td style="text-align: left;">−$30</td>
</tr>
<tr class="even">
<td style="text-align: left;">30</td>
<td style="text-align: left;">$126</td>
<td style="text-align: left;">$120</td>
<td style="text-align: left;">−$6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">40</td>
<td style="text-align: left;">$138</td>
<td style="text-align: left;">$160</td>
<td style="text-align: left;">$22</td>
</tr>
<tr class="even">
<td style="text-align: left;">50</td>
<td style="text-align: left;">$150</td>
<td style="text-align: left;">$200</td>
<td style="text-align: left;">$50</td>
</tr>
<tr class="odd">
<td style="text-align: left;">60</td>
<td style="text-align: left;">$165</td>
<td style="text-align: left;">$240</td>
<td style="text-align: left;">$75</td>
</tr>
<tr class="even">
<td style="text-align: left;">70</td>
<td style="text-align: left;">$190</td>
<td style="text-align: left;">$280</td>
<td style="text-align: left;">$90</td>
</tr>
<tr class="odd">
<td style="text-align: left;">80</td>
<td style="text-align: left;">$230</td>
<td style="text-align: left;">$320</td>
<td style="text-align: left;">$90</td>
</tr>
<tr class="even">
<td style="text-align: left;">90</td>
<td style="text-align: left;">$296</td>
<td style="text-align: left;">$360</td>
<td style="text-align: left;">$64</td>
</tr>
<tr class="odd">
<td style="text-align: left;">100</td>
<td style="text-align: left;">$400</td>
<td style="text-align: left;">$400</td>
<td style="text-align: left;">$0</td>
</tr>
<tr class="even">
<td style="text-align: left;">110</td>
<td style="text-align: left;">$550</td>
<td style="text-align: left;">$440</td>
<td style="text-align: left;">$−110</td>
</tr>
<tr class="odd">
<td style="text-align: left;">120</td>
<td style="text-align: left;">$715</td>
<td style="text-align: left;">$480</td>
<td style="text-align: left;">$−235</td>
</tr>
</tbody>
</table>
<p>Table 8.1 Total Cost and Total Revenue at the Raspberry Farm</p>
<p>Based on its total revenue and total cost curves, a perfectly competitive firm like the raspberry farm can calculate the quantity of output that will provide the highest level of profit. At any given quantity, total revenue minus total cost will equal profit. One way to determine the most profitable quantity to produce is to see at what quantity total revenue exceeds total cost by the largest amount. <a href="#CNX_Econ_C08_001">Figure 8.2</a> shows total revenue, total cost and profit using the data from <a href="#ch08mod02_tab01">Table 8.1</a>. The vertical gap between total revenue and total cost is profit, for example, at Q = 60, TR = 240 and TC = 165. The difference is 75, which is the height of the profit curve at that output level. The firm doesn’t make a profit at every level of output. In this example, total costs will exceed total revenues at output levels from 0 to approximately 30, and so over this range of output, the firm will be making losses. At output levels from 40 to 100, total revenues exceed total costs, so the firm is earning profits. However, at any output greater than 100, total costs again exceed total revenues and the firm is making increasing losses. Total profits appear in the final column of <a href="#ch08mod02_tab01">Table 8.1</a>. Maximum profit occurs at an output between 70 and 80, when profit equals $90.</p>
<p>A higher price would mean that total revenue would be higher for every quantity sold. A lower price would mean that total revenue would be lower for every quantity sold. What happens if the price drops low enough so that the total revenue line is completely below the total cost curve; that is, at every level of output, total costs are higher than total revenues? In this instance, the best the firm can do is to suffer losses. However, a profit-maximizing firm will prefer the quantity of output where total revenues come closest to total costs and thus where the losses are smallest.</p>
<p>(Later we will see that sometimes it will make sense for the firm to close, rather than stay in operation producing output.)</p>
</section>
<section id="comparing-marginal-revenue-and-marginal-costs" class="level3">
<h3 class="anchored" data-anchor-id="comparing-marginal-revenue-and-marginal-costs">Comparing Marginal Revenue and Marginal Costs</h3>
<p>The approach that we described in the previous section, using total revenue and total cost, is not the only approach to determining the profit maximizing level of output. In this section, we provide an alternative approach which uses marginal revenue and marginal cost.</p>
<p>Firms often do not have the necessary data they need to draw a complete total cost curve for all levels of production. They cannot be sure of what total costs would look like if they, say, doubled production or cut production in half, because they have not tried it. Instead, firms experiment. They produce a slightly greater or lower quantity and observe how it affects profits. In economic terms, this practical approach to maximizing profits means examining how changes in production affect marginal revenue and marginal cost.</p>
<p><a href="#CNX_Econ_C08_002">Figure 8.3</a> presents the marginal revenue and marginal cost curves based on the total revenue and total cost in <a href="#ch08mod02_tab01">Table 8.1</a>. The marginal revenue curve shows the additional revenue gained from selling one more unit. As mentioned before, a firm in perfect competition faces a perfectly elastic demand curve for its product—that is, the firm’s demand curve is a horizontal line drawn at the market price level. This also means that the firm’s marginal revenue curve is the same as the firm’s demand curve: Every time a consumer demands one more unit, the firm sells one more unit and revenue increases by exactly the same amount equal to the market price. In this example, every time the firm sells a pack of frozen raspberries, the firm’s revenue increases by $4. <a href="#ch08mod02_tab02">Table 8.2</a> shows an example of this. This condition only holds for price taking firms in perfect competition where:</p>
<p><span class="math inline">\(\text{marginal~revenue~=~price}\)</span></p>
<p>The formula for marginal revenue is:</p>
<p><span class="math inline">\(\text{marginal~revenue~=~}\frac{\text{change~in~total~revenue}}{\text{change~in~quantity}}\)</span></p>
<p>Table 8.2</p>
<p>Notice that marginal revenue does not change as the firm produces more output. That is because under perfect competition, the price is determined through the interaction of supply and demand in the market and does not change as the farmer produces more (keeping in mind that, due to the relative small size of each firm, increasing their supply has no impact on the total market supply where price is determined).</p>
<p>Since a perfectly competitive firm is a price taker, it can sell whatever quantity it wishes at the market-determined price. We calculate marginal cost, the cost per additional unit sold, by dividing the change in total cost by the change in quantity. The formula for marginal cost is:</p>
<p><span class="math inline">\(\text{marginal~cost~=~}\frac{\text{change~in~total~cost}}{\text{change~in~quantity}}\)</span></p>
<p>Ordinarily, marginal cost changes as the firm produces a greater quantity.</p>
<p>In the raspberry farm example, in <a href="#CNX_Econ_C08_002">Figure 8.3</a> and <a href="#ch08mod02_tab03">Table 8.3</a>, marginal cost at first declines as production increases from 10 to 20 to 30 to 40 packs of raspberries—which represents the area of increasing marginal returns that is not uncommon at low levels of production. At some point, though, marginal costs start to increase, displaying the typical pattern of diminishing marginal returns. If the firm is producing at a quantity where MR &gt; MC, like 40 or 50 packs of raspberries, then it can increase profit by increasing output because the marginal revenue is exceeding the marginal cost. If the firm is producing at a quantity where MC &gt; MR, like 90 or 100 packs, then it can increase profit by reducing output because the reductions in marginal cost will exceed the reductions in marginal revenue. The firm’s profit-maximizing choice of output will occur where MR = MC (or at a choice close to that point).</p>
<p><img src="media/8-2-how-perfectly-competitive-firms-make-output-decisions_rId38.jpeg" style="width:4.88in;height:2.605in"></p>
<p>Figure 8.3 Marginal Revenues and Marginal Costs at the Raspberry Farm: Individual Farmer For a perfectly competitive firm, the marginal revenue (MR) curve is a horizontal line because it is equal to the price of the good, which is determined by the market, as <a href="#CNX_Econ_C08_015">Figure 8.4</a> illustrates. The marginal cost (MC) curve is sometimes initially downward-sloping, if there is a region of increasing marginal returns at low levels of output, but is eventually upward-sloping at higher levels of output as diminishing marginal returns kick in.</p>
<p><img src="media/8-2-how-perfectly-competitive-firms-make-output-decisions_rId41.jpeg" style="width:4.88in;height:2.655in"></p>
<p>Figure 8.4 Supply, Demand, and Equilibrium Price in the Market for Raspberries The equilibrium price of raspberries is determined through the interaction of market supply and market demand at $4.00.</p>
<p>Table 8.3 Marginal Revenues and Marginal Costs at the Raspberry Farm</p>
<p>In this example, the marginal revenue and marginal cost curves cross at a price of $4 and a quantity of 80 produced. If the farmer started out producing at a level of 60, and then experimented with increasing production to 70, marginal revenues from the increase in production would exceed marginal costs—and so profits would rise. The farmer has an incentive to keep producing. At a level of output of 80, marginal cost and marginal revenue are equal so profit doesn’t change. If the farmer then experimented further with increasing production from 80 to 90, he would find that marginal costs from the increase in production are greater than marginal revenues, and so profits would decline.</p>
<p>The profit-maximizing choice for a perfectly competitive firm will occur at the level of output where marginal revenue is equal to marginal cost—that is, where MR = MC. This occurs at Q = 80 in the figure.</p>
</section>
<section id="work-it-out" class="level3 Heading3Grey">
<h3 class="Heading3Grey anchored" data-anchor-id="work-it-out">Work It Out</h3>
<section id="does-profit-maximization-occur-at-a-range-of-output-or-a-specific-level-of-output" class="level4 Heading4Grey">
<h4 class="Heading4Grey anchored" data-anchor-id="does-profit-maximization-occur-at-a-range-of-output-or-a-specific-level-of-output">Does Profit Maximization Occur at a Range of Output or a Specific Level of Output?</h4>
<p><a href="#ch08mod02_tab01">Table 8.1</a> shows that maximum profit occurs at any output level between 70 and 80 units of output. But MR = MC occurs only at 80 units of output. How can we explain this slight discrepancy? As long as MR &gt; MC, a profit-seeking firm should keep expanding production. Expanding production into the zone where MR &lt; MC reduces economic profits. It’s true that profit is the same at Q = 70 and Q = 80, but it’s only when the firm goes beyond that Q that it will see that profits fall. Thus, MR = MC is the signal to stop expanding, so that is the level of output they should target.</p>
<p>Because the marginal revenue received by a perfectly competitive firm is equal to the price P, we can also write the profit-maximizing rule for a perfectly competitive firm as a recommendation to produce at the quantity of output where P = MC.</p>
</section>
</section>
<section id="profits-and-losses-with-the-average-cost-curve" class="level3">
<h3 class="anchored" data-anchor-id="profits-and-losses-with-the-average-cost-curve">Profits and Losses with the Average Cost Curve</h3>
<p>Does maximizing profit (producing where MR = MC) imply an actual economic profit? The answer depends on the relationship between price and average total cost, which is the average profit or profit margin. If the market price is higher than the firm's average cost of production for that quantity produced, then the profit margin is positive and the firm will earn profits. Conversely, if the market price is lower than the average cost of production, the profit margin is negative and the firm will suffer losses. You might think that, in this situation, the firm may want to shut down immediately. Remember, however, that the firm has already paid for fixed costs, such as equipment, so it may continue to produce for a while and incur a loss. <a href="#ch08mod02_tab03">Table 8.3</a> continues the raspberry farm example. <a href="#CNX_Econ_C08_014">Figure 8.5</a> illustrates the three possible scenarios: (a) where price intersects marginal cost at a level above the average cost curve, (b) where price intersects marginal cost at a level equal to the average cost curve, and (c) where price intersects marginal cost at a level below the average cost curve.</p>
<p><img src="media/8-2-how-perfectly-competitive-firms-make-output-decisions_rId49.jpeg" style="width:6.5in;height:5.935in"></p>
<p>Figure 8.5 Price and Average Cost at the Raspberry Farm In (a), price intersects marginal cost above the average cost curve. Since price is greater than average cost, the firm is making a profit. In (b), price intersects marginal cost at the minimum point of the average cost curve. Since price is equal to average cost, the firm is breaking even. In (c), price intersects marginal cost below the average cost curve. Since price is less than average cost, the firm is making a loss.</p>
<p>First consider a situation where the price is equal to $5 for a pack of frozen raspberries. The rule for a profit-maximizing perfectly competitive firm is to produce the level of output where Price= MR = MC, so the raspberry farmer will produce a quantity of approximately 85, which is labeled as E' in <a href="#CNX_Econ_C08_014">Figure 8.5</a> (a). Remember that the area of a rectangle is equal to its base multiplied by its height. The farm’s total revenue at this price will be shown by the rectangle from the origin over to a quantity of 85 packs (the base) up to point E' (the height), over to the price of $5, and back to the origin. The average cost of producing 80 packs is shown by point C or about $3.50. Total costs will be the quantity of 85 times the average cost of $3.50, which is shown by the area of the rectangle from the origin to a quantity of 90, up to point C, over to the vertical axis and down to the origin. The difference between total revenues and total costs is profits. Thus, profits will be the blue shaded rectangle on top.</p>
<p>We calculate this as:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="media/rId52.png" style="width:2.52083in;height:0.61458in" class="figure-img"></p>
<figcaption class="figure-caption">multiline equation row 1 profit equals total revenue minus total cost row 2 Blank equals left parenthesis 85 right parenthesis times left parenthesis dollar sign 5.00 right parenthesis minus left parenthesis 85 right parenthesis times left parenthesis dollar sign 3.50 right parenthesis row 3 Blank equals dollar sign 127.50</figcaption>
</figure>
</div>
<p>Or, we can calculate it as:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="media/rId54.png" style="width:3in;height:0.61458in" class="figure-img"></p>
<figcaption class="figure-caption">multiline equation row 1 profit equals left parenthesis price en dash average cost right parenthesis times quantity row 2 Blank equals left parenthesis dollar sign 5.00 en dash dollar sign 3.50 right parenthesis times 85 row 3 Blank equals dollar sign 127.50</figcaption>
</figure>
</div>
<p>Now consider <a href="#CNX_Econ_C08_014">Figure 8.5</a> (b), where the price has fallen to $2.75 for a pack of frozen raspberries. Again, the perfectly competitive firm will choose the level of output where Price = MR = MC, but in this case, the quantity produced will be 75. At this price and output level, where the marginal cost curve is crossing the average cost curve, the price the firm receives is exactly equal to its average cost of production. We call this the break even point.</p>
<p>The farm’s total revenue at this price will be shown by the large shaded rectangle from the origin over to a quantity of 75 packs (the base) up to point E (the height), over to the price of $2.75, and back to the origin. The height of the average cost curve at Q = 75, i.e.&nbsp;point E, shows the average cost of producing this quantity. Total costs will be the quantity of 75 times the average cost of $2.75, which is shown by the area of the rectangle from the origin to a quantity of 75, up to point E, over to the vertical axis and down to the origin. It should be clear that the rectangles for total revenue and total cost are the same. Thus, the firm is making zero profit. The calculations are as follows:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="media/rId57.png" style="width:2.4375in;height:0.61458in" class="figure-img"></p>
<figcaption class="figure-caption">multiline equation row 1 profit equals total revenue en dash total cost row 2 Blank equals left parenthesis 75 right parenthesis left parenthesis dollar sign 2.75 right parenthesis en dash left parenthesis 75 right parenthesis left parenthesis dollar sign 2.75 right parenthesis row 3 Blank equals dollar sign zero</figcaption>
</figure>
</div>
<p>Or, we can calculate it as:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="media/rId59.png" style="width:2.97917in;height:0.61458in" class="figure-img"></p>
<figcaption class="figure-caption">multiline equation row 1 profit equals left parenthesis price en dash average cost right parenthesis times quantity row 2 Blank equals left parenthesis dollar sign 2.75 en dash dollar sign 2.75 right parenthesis times 75 row 3 Blank equals dollar sign zero</figcaption>
</figure>
</div>
<p>In <a href="#CNX_Econ_C08_014">Figure 8.5</a> (c), the market price has fallen still further to $2.00 for a pack of frozen raspberries. At this price, marginal revenue intersects marginal cost at a quantity of 65. The farm’s total revenue at this price will be shown by the large shaded rectangle from the origin over to a quantity of 65 packs (the base) up to point E” (the height), over to the price of $2, and back to the origin. The average cost of producing 65 packs is shown by Point C” or shows the average cost of producing 50 packs is about $2.73. Total costs will be the quantity of 65 times the average cost of $2.73, which the area of the rectangle from the origin to a quantity of 50, up to point C”, over to the vertical axis and down to the origin shows. It should be clear from examining the two rectangles that total revenue is less than total cost. Thus, the firm is losing money and the loss (or negative profit) will be the rose-shaded rectangle.</p>
<p>The calculations are:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="media/rId61.png" style="width:2.60417in;height:0.61458in" class="figure-img"></p>
<figcaption class="figure-caption">multiline equation row 1 profit equals left parenthesis total revenue en dash total cost right parenthesis row 2 Blank equals left parenthesis 65 right parenthesis left parenthesis dollar sign 2.00 right parenthesis en dash left parenthesis 65 right parenthesis left parenthesis dollar sign 2.73 right parenthesis row 3 Blank equals en dash dollar sign 47.45</figcaption>
</figure>
</div>
<p>Or:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="media/rId63.png" style="width:3in;height:0.61458in" class="figure-img"></p>
<figcaption class="figure-caption">multiline equation row 1 profit equals left parenthesis price en dash average cost right parenthesis times quantity row 2 Blank equals left parenthesis dollar sign 2.00 en dash dollar sign 2.73 right parenthesis times 65 row 3 Blank equals en dash dollar sign 47.45</figcaption>
</figure>
</div>
<p>If the market price that perfectly competitive firm receives leads it to produce at a quantity where the price is greater than average cost, the firm will earn profits. If the price the firm receives causes it to produce at a quantity where price equals average cost, which occurs at the minimum point of the AC curve, then the firm earns zero profits. Finally, if the price the firm receives leads it to produce at a quantity where the price is less than average cost, the firm will earn losses. <a href="#ch08mod02_tab04">Table 8.4</a> summarizes this.</p>
<p>Table 8.4</p>
</section>
<section id="clear-it-up" class="level3 Heading3Grey">
<h3 class="Heading3Grey anchored" data-anchor-id="clear-it-up">Clear It Up</h3>
<section id="which-intersection-should-a-firm-choose" class="level4 Heading4Grey">
<h4 class="Heading4Grey anchored" data-anchor-id="which-intersection-should-a-firm-choose">Which intersection should a firm choose?</h4>
<p>At a price of $2, MR intersects MC at two points: Q = 20 and Q = 65. It never makes sense for a firm to choose a level of output on the downward sloping part of the MC curve, because the profit is lower (the loss is bigger). Thus, the correct choice of output is Q = 65.</p>
</section>
</section>
<section id="the-shutdown-point" class="level3">
<h3 class="anchored" data-anchor-id="the-shutdown-point">The Shutdown Point</h3>
<p>The possibility that a firm may earn losses raises a question: Why can the firm not avoid losses by shutting down and not producing at all? The answer is that shutting down can reduce variable costs to zero, but in the short run, the firm has already paid for fixed costs. As a result, if the firm produces a quantity of zero, it would still make losses because it would still need to pay for its fixed costs. Therefore when a firm is experiencing losses, it must face a question: should it continue producing or should it shut down?</p>
<p>As an example, consider the situation of the Yoga Center, which has signed a contract to rent space that costs $10,000 per month. If the firm decides to operate, its marginal costs for hiring yoga teachers is $15,000 for the month. If the firm shuts down, it must still pay the rent, but it would not need to hire labor. <a href="#ch08mod02_tab05">Table 8.5</a> shows three possible scenarios. In the first scenario, the Yoga Center does not have any clients, and therefore does not make any revenues, in which case it faces losses of $10,000 equal to the fixed costs. In the second scenario, the Yoga Center has clients that earn the center revenues of $10,000 for the month, but ultimately experiences losses of $15,000 due to having to hire yoga instructors to cover the classes. In the third scenario, the Yoga Center earns revenues of $20,000 for the month, but experiences losses of $5,000.</p>
<p>In all three cases, the Yoga Center loses money. In all three cases, when the rental contract expires in the long run, assuming revenues do not improve, the firm should exit this business. In the short run, though, the decision varies depending on the level of losses and whether the firm can cover its variable costs. In scenario 1, the center does not have any revenues, so hiring yoga teachers would increase variable costs and losses, so it should shut down and only incur its fixed costs. In scenario 2, the center’s losses are greater because it does not make enough revenue to offset the increased variable costs, so it should shut down immediately and only incur its fixed costs. If price is below the minimum average variable cost, the firm must shut down. In contrast, in scenario 3 the revenue that the center can earn is high enough that the losses diminish when it remains open, so the center should remain open in the short run.</p>
<table class="table">
<colgroup>
<col style="width: 97%">
</colgroup>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Scenario 1</strong></td>
</tr>
<tr class="even">
<td style="text-align: left;">If the center shuts down now, revenues are zero but it will not incur any variable costs and would only need to pay fixed costs of $10,000.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><img src="media/rId68.png" style="width:3.52083in;height:0.61458in" alt="multiline equation line 1 profit equals total revenue en dash left parenthesis fixed costs plus variable cost right parenthesis line 2 equals zero en dash dollar sign 10,000 line 3 equals en dash dollar sign 10,000"></td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Scenario 2</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left;">The center earns revenues of $10,000, and variable costs are $15,000. The center should shut down now.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><img src="media/rId70.png" style="width:3.625in;height:0.61458in" alt="multiline equation line 1 profit equals total revenue en dash left parenthesis fixed costs plus variable cost right parenthesis line 2 equals dollar sign 10,000 en dash left parenthesis dollar sign 10,000 plus dollar sign 15,000 right parenthesis line 3 equals en dash dollar sign 15,000"></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Scenario 3</strong></td>
</tr>
<tr class="even">
<td style="text-align: left;">The center earns revenues of $20,000, and variable costs are $15,000. The center should continue in business.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><img src="media/rId72.png" style="width:3.625in;height:0.61458in" alt="multiline equation line 1 profit equals total revenue en dash left parenthesis fixed costs plus variable cost right parenthesis line 2 equals dollar sign 20,000 en dash left parenthesis dollar sign 10,000 plus dollar sign 15,000 right parenthesis line 3 equals en dash dollar sign 5,000"></td>
</tr>
</tbody>
</table>
<p>Table 8.5 Should the Yoga Center Shut Down Now or Later?</p>
<p><a href="#CNX_Econ_C08_012">Figure 8.6</a> illustrates the lesson that remaining open requires the price to exceed the firm’s average variable cost. When the firm is operating below the break-even point, where price equals average cost, it is operating at a loss so it faces two options: continue to produce and lose money or shutdown. Which option is preferable? The one that loses the least money is the best choice.</p>
<p>At a price of $2.00 per pack, as Figure 8.6 (a) illustrates, if the farm stays in operation it will produce at a level of 65 packs of raspberries, and it will make losses of $47.45 (as explained earlier). The alternative would be to shut down and lose all the fixed costs of $62.00. Since losing $47.45 is preferable to losing $62.00, the profit maximizing (or in this case the loss minimizing) choice is to stay in operation. The key reason is because price is above average variable cost. This means that at the current price the farm can pay all its variable costs, and have some revenue left over to pay some of the fixed costs. So the loss represents the part of the fixed costs the farm can’t pay, which is less than the entire fixed costs. However, if the price declined to $1.50 per pack, as <a href="#CNX_Econ_C08_012">Figure 8.6</a> (b) shows, and if the firm applied its rule of producing where P = MR = MC, it would produce a quantity of 60. This price is below average variable cost for this level of output. If the farmer cannot pay workers (the variable costs), then it has to shut down. At this price and output, total revenues would be $90 (quantity of 60 times price of $1.50) and total cost would be $165, for overall losses of $75. If the farm shuts down, it must pay only its fixed costs of $62, so shutting down is preferable to selling at a price of $1.50 per pack.</p>
<p><img src="media/8-2-how-perfectly-competitive-firms-make-output-decisions_rId74.jpeg" style="width:6.5in;height:2.73in"></p>
<p>Figure 8.6 The Shutdown Point for the Raspberry Farm In (a), the farm produces at a level of 65. It is making losses of $47.50, but price is above average variable cost, so it continues to operate. In (b), total revenues are $90 and total cost is $165, for overall losses of $75. If the farm shuts down, it must pay only its fixed costs of $62. Shutting down is preferable to selling at a price of $1.50 per pack.</p>
<p>Looking at <a href="#ch08mod02_tab06">Table 8.6</a>, if the price falls below about $1.72, the minimum average variable cost, the firm must shut down.</p>
<table class="table">
<colgroup>
<col style="width: 24%">
<col style="width: 24%">
<col style="width: 24%">
<col style="width: 24%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Quantity<br>
Q</th>
<th style="text-align: left;">Average Variable Cost<br>
AVC</th>
<th style="text-align: left;">Average Cost<br>
AC</th>
<th style="text-align: left;">Marginal Cost<br>
MC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">0</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
</tr>
<tr class="even">
<td style="text-align: left;">10</td>
<td style="text-align: left;">$2.80</td>
<td style="text-align: left;">$9.00</td>
<td style="text-align: left;">$2.80</td>
</tr>
<tr class="odd">
<td style="text-align: left;">20</td>
<td style="text-align: left;">$2.40</td>
<td style="text-align: left;">$5.50</td>
<td style="text-align: left;">$2.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">30</td>
<td style="text-align: left;">$2.13</td>
<td style="text-align: left;">$4.20</td>
<td style="text-align: left;">$1.60</td>
</tr>
<tr class="odd">
<td style="text-align: left;">40</td>
<td style="text-align: left;">$1.90</td>
<td style="text-align: left;">$3.45</td>
<td style="text-align: left;">$1.20</td>
</tr>
<tr class="even">
<td style="text-align: left;">50</td>
<td style="text-align: left;">$1.76</td>
<td style="text-align: left;">$3.00</td>
<td style="text-align: left;">$1.20</td>
</tr>
<tr class="odd">
<td style="text-align: left;">60</td>
<td style="text-align: left;">$1.72</td>
<td style="text-align: left;">$2.75</td>
<td style="text-align: left;">$1.50</td>
</tr>
<tr class="even">
<td style="text-align: left;">70</td>
<td style="text-align: left;">$1.83</td>
<td style="text-align: left;">$2.71</td>
<td style="text-align: left;">$2.50</td>
</tr>
<tr class="odd">
<td style="text-align: left;">80</td>
<td style="text-align: left;">$2.10</td>
<td style="text-align: left;">$2.88</td>
<td style="text-align: left;">$4.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">90</td>
<td style="text-align: left;">$2.60</td>
<td style="text-align: left;">$3.29</td>
<td style="text-align: left;">$6.60</td>
</tr>
<tr class="odd">
<td style="text-align: left;">100</td>
<td style="text-align: left;">$3.38</td>
<td style="text-align: left;">$4.00</td>
<td style="text-align: left;">$10.40</td>
</tr>
<tr class="even">
<td style="text-align: left;">110</td>
<td style="text-align: left;">$4.44</td>
<td style="text-align: left;">$5.00</td>
<td style="text-align: left;">$15.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">120</td>
<td style="text-align: left;">$5.44</td>
<td style="text-align: left;">$5.96</td>
<td style="text-align: left;">$31.50</td>
</tr>
</tbody>
</table>
<p>Table 8.6 Cost of Production for the Raspberry Farm</p>
<p>The intersection of the average variable cost curve and the marginal cost curve, which shows the price below which the firm would lack enough revenue to cover its variable costs, is called the <strong>shutdown point</strong>. If the perfectly competitive firm faces a market price above the shutdown point, then the firm is at least covering its average variable costs. At a price above the shutdown point, the firm is also making enough revenue to cover at least a portion of fixed costs, so it should limp ahead even if it is making losses in the short run, since at least those losses will be smaller than if the firm shuts down immediately and incurs a loss equal to total fixed costs. However, if the firm is receiving a price below the price at the shutdown point, then the firm is not even covering its variable costs. In this case, staying open is making the firm’s losses larger, and it should shut down immediately. To summarize, if:</p>
<ul>
<li>price &lt; minimum average variable cost, then firm shuts down</li>
<li>price &gt; minimum average variable cost, then firm stays in business</li>
</ul>
</section>
<section id="short-run-outcomes-for-perfectly-competitive-firms" class="level3">
<h3 class="anchored" data-anchor-id="short-run-outcomes-for-perfectly-competitive-firms">Short-Run Outcomes for Perfectly Competitive Firms</h3>
<p>The average cost and average variable cost curves divide the marginal cost curve into three segments, as <a href="#CNX_Econ_C08_008">Figure 8.7</a> shows. At the market price, which the perfectly competitive firm accepts as given, the profit-maximizing firm chooses the output level where price or marginal revenue, which are the same thing for a perfectly competitive firm, is equal to marginal cost: P = MR = MC.</p>
<p><img src="media/8-2-how-perfectly-competitive-firms-make-output-decisions_rId79.jpeg" style="width:4.88in;height:3.38in"></p>
<p>Figure 8.7 Profit, Loss, Shutdown We can divide the marginal cost curve into three zones, based on where it is crossed by the average cost and average variable cost curves. We call the point where MC crosses AC the break even point. If the firm is operating where the market price is at a level higher than the break even point, then price will be greater than average cost and the firm is earning profits. If the price is exactly at the break even point, then the firm is making zero profits. If price falls in the zone between the shutdown point and the break even point, then the firm is making losses but will continue to operate in the short run, since it is covering its variable costs, and more if price is above the shutdown-point price. However, if price falls below the price at the shutdown point, then the firm will shut down immediately, since it is not even covering its variable costs.</p>
<p>First consider the upper zone, where prices are above the level where marginal cost (MC) crosses average cost (AC) at the zero profit point. At any price above that level, the firm will earn profits in the short run. If the price falls exactly on the break even point where the MC and AC curves cross, then the firm earns zero profits. If a price falls into the zone between the break even point, where MC crosses AC, and the shutdown point, where MC crosses AVC, the firm will be making losses in the short run—but since the firm is more than covering its variable costs, the losses are smaller than if the firm shut down immediately. Finally, consider a price at or below the shutdown point where MC crosses AVC. At any price like this one, the firm will shut down immediately, because it cannot even cover its variable costs.</p>
</section>
<section id="marginal-cost-and-the-firms-supply-curve" class="level3">
<h3 class="anchored" data-anchor-id="marginal-cost-and-the-firms-supply-curve">Marginal Cost and the Firm’s Supply Curve</h3>
<p>For a perfectly competitive firm, the marginal cost curve is identical to the firm’s supply curve starting from the minimum point on the average variable cost curve. To understand why this perhaps surprising insight holds true, first think about what the supply curve means. A firm checks the market price and then looks at its supply curve to decide what quantity to produce. Now, think about what it means to say that a firm will maximize its profits by producing at the quantity where P = MC. This rule means that the firm checks the market price, and then looks at its marginal cost to determine the quantity to produce—and makes sure that the price is greater than the minimum average variable cost. In other words, the marginal cost curve above the minimum point on the average variable cost curve becomes the firm’s supply curve.</p>
</section>
<section id="link-it-up" class="level3 Heading3Grey">
<h3 class="Heading3Grey anchored" data-anchor-id="link-it-up">Link It Up</h3>
<p>Watch this <a href="http://openstax.org/l/foodprice">video</a> that addresses how drought in the United States can impact food prices across the world.</p>
<p>As we discussed in the chapter on <a href="http://openstax.org/books/principles-microeconomics-3e/pages/3-introduction-to-demand-and-supply">Demand and Supply</a>, many of the reasons that supply curves shift relate to underlying changes in costs. For example, a lower price of key inputs or new technologies that reduce production costs cause supply to shift to the right. In contrast, bad weather or added government regulations can add to costs of certain goods in a way that causes supply to shift to the left. We can also interpret these shifts in the firm’s supply curve as shifts of the marginal cost curve. A shift in costs of production that increases marginal costs at all levels of output—and shifts MC upward and to the left—will cause a perfectly competitive firm to produce less at any given market price. Conversely, a shift in costs of production that decreases marginal costs at all levels of output will shift MC downward and to the right and as a result, a competitive firm will choose to expand its level of output at any given price. The following Work It Out feature will walk you through an example.</p>
</section>
<section id="work-it-out-1" class="level3 Heading3Grey">
<h3 class="Heading3Grey anchored" data-anchor-id="work-it-out-1">Work It Out</h3>
<section id="at-what-price-should-the-firm-continue-producing-in-the-short-run" class="level4 Heading4Grey">
<h4 class="Heading4Grey anchored" data-anchor-id="at-what-price-should-the-firm-continue-producing-in-the-short-run">At What Price Should the Firm Continue Producing in the Short Run?</h4>
<p>To determine the short-run economic condition of a firm in perfect competition, follow the steps outlined below. Use the data in <a href="#ch08mod02_tab07">Table 8.7</a>.</p>
<p>Table 8.7</p>
<p>Step 1. Determine the cost structure for the firm. For a given total fixed costs and variable costs, calculate total cost, average variable cost, average total cost, and marginal cost. Follow the formulas given in the <a href="http://openstax.org/books/principles-microeconomics-3e/pages/7-introduction-to-production-costs-and-industry-structure">Production, Costs, and Industry Structure</a> chapter. These calculations are in <a href="#ch08mod02_tab08">Table 8.8</a>.</p>
<table class="table">
<colgroup>
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 16%">
<col style="width: 15%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Q</th>
<th style="text-align: left;">P</th>
<th style="text-align: left;">TFC</th>
<th style="text-align: left;">TVC</th>
<th style="text-align: left;">TC<br>
(TFC+TVC)</th>
<th style="text-align: left;">AVC<br>
(TVC/Q)</th>
<th style="text-align: left;">ATC<br>
(TC/Q)</th>
<th style="text-align: left;">MC<br>
(TC<sub>2</sub>−TC<sub>1</sub>)/<br>
(Q<sub>2</sub>−Q<sub>1</sub>)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">0</td>
<td style="text-align: left;">$28</td>
<td style="text-align: left;">$20</td>
<td style="text-align: left;">$0</td>
<td style="text-align: left;">$20+$0=$20</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
</tr>
<tr class="even">
<td style="text-align: left;">1</td>
<td style="text-align: left;">$28</td>
<td style="text-align: left;">$20</td>
<td style="text-align: left;">$20</td>
<td style="text-align: left;">$20+$20=$40</td>
<td style="text-align: left;">$20/1=$20.00</td>
<td style="text-align: left;">$40/1=$40.00</td>
<td style="text-align: left;">($40−$20)/<br>
(1−0)= $20</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2</td>
<td style="text-align: left;">$28</td>
<td style="text-align: left;">$20</td>
<td style="text-align: left;">$25</td>
<td style="text-align: left;">$20+$25=$45</td>
<td style="text-align: left;">$25/2=$12.50</td>
<td style="text-align: left;">$45/2=$22.50</td>
<td style="text-align: left;">($45−$40)/<br>
(2−1)= $5</td>
</tr>
<tr class="even">
<td style="text-align: left;">3</td>
<td style="text-align: left;">$28</td>
<td style="text-align: left;">$20</td>
<td style="text-align: left;">$35</td>
<td style="text-align: left;">$20+$35=$55</td>
<td style="text-align: left;">$35/3=$11.67</td>
<td style="text-align: left;">$55/3=$18.33</td>
<td style="text-align: left;">($55−$45)/<br>
(3−2)= $10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">4</td>
<td style="text-align: left;">$28</td>
<td style="text-align: left;">$20</td>
<td style="text-align: left;">$52</td>
<td style="text-align: left;">$20+$52=$72</td>
<td style="text-align: left;">$52/4=$13.00</td>
<td style="text-align: left;">$72/4=$18.00</td>
<td style="text-align: left;">($72−$55)/<br>
(4−3)= $17</td>
</tr>
<tr class="even">
<td style="text-align: left;">5</td>
<td style="text-align: left;">$28</td>
<td style="text-align: left;">$20</td>
<td style="text-align: left;">$80</td>
<td style="text-align: left;">$20+$80=$100</td>
<td style="text-align: left;">$80/5=$16.00</td>
<td style="text-align: left;">$100/5=$20.00</td>
<td style="text-align: left;">($100−$72)/<br>
(5−4)= $28</td>
</tr>
</tbody>
</table>
<p>Table 8.8</p>
<p>Step 2. Determine the market price that the firm receives for its product. Since the firm in perfect competition is a price taker, the market price is constant. With the given price, calculate total revenue as equal to price multiplied by quantity for all output levels produced. In this example, the given price is $28. You can see that in the second column of <a href="#ch08mod02_tab09">Table 8.9</a>.</p>
<p>Table 8.9</p>
<p>Step 3. Calculate profits as total cost subtracted from total revenue, as <a href="#ch08mod02_tab10">Table 8.10</a> shows.</p>
<p>Table 8.10</p>
<p>Step 4. To find the profit-maximizing output level, look at the Marginal Cost column (at every output level produced), as <a href="#ch08mod02_tab11">Table 8.11</a> shows, and determine where it is equal to the market price. The output level where price equals the marginal cost is the output level that maximizes profits.</p>
<p>Table 8.11</p>
<p>Step 5. Once you have determined the profit-maximizing output level (in this case, output quantity 5), you can look at the amount of profits made (in this case, $40).</p>
<p>Step 6. If the firm is making economic losses, the firm needs to determine whether it produces the output level where price equals marginal revenue and equals marginal cost or it shuts down and only incurs its fixed costs.</p>
<p>Step 7. For the output level where marginal revenue is equal to marginal cost, check if the market price is greater than the average variable cost of producing that output level.</p>
<ul>
<li>If P &gt; AVC but P &lt; ATC, then the firm continues to produce in the short-run, making economic losses.</li>
<li>If P &lt; AVC, then the firm stops producing and only incurs its fixed costs.</li>
</ul>
<p>In this example, the price of $28 is greater than the AVC ($16.40) of producing 5 units of output, so the firm continues producing.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./8-1-perfect-competition-and-why-it-matters.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">8.1 Perfect Competition and Why It Matters</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./8-3-entry-and-exit-decisions-in-the-long-run.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-title">8.3 Entry and Exit Decisions in the Long Run</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>