## 19.4 The Benefits of Reducing Barriers to International Trade

### Learning Objectives

By the end of this section, you will be able to:

-   Explain tariffs as barriers to trade
-   Identify at least two benefits of reducing barriers to international
    trade

Tariffs are taxes that governments place on imported goods for a variety
of reasons. Some of these reasons include protecting sensitive
industries, for humanitarian reasons, and protecting against dumping.
Traditionally, tariffs were used simply as a political tool to protect
certain vested economic, social, and cultural interests. The World Trade
Organization (WTO) is committed to lowering barriers to trade. The
world's nations meet through the WTO to negotiate how they can reduce
barriers to trade, such as tariffs. WTO negotiations happen in "rounds,"
where all countries negotiate one agreement to encourage trade, take a
year or two off, and then start negotiating a new agreement. The current
round of negotiations is called the Doha Round because it was officially
launched in Doha, the capital city of Qatar, in November 2001. In 2010,
the WTO noted that the Doha Round's emphasis on market access and
reforms of agricultural subsidies could add \$121--\$202 billion to the
world economy.

In the context of a global economy that currently produces more than
\$80 trillion of goods and services each year, this amount is not large:
it is an increase of less than 1%. But before dismissing the gains from
trade too quickly, it is worth remembering two points.

-   First, a gain of a few hundred billion dollars is enough money to
    deserve attention! Moreover, remember that this increase is not a
    one-time event; it would persist each year into the future.
-   Second, the estimate of gains may be on the low side because some of
    the gains from trade are not measured especially well in economic
    statistics. For example, it is difficult to measure the potential
    advantages to consumers of having a variety of products available
    and a greater degree of competition among producers. Perhaps the
    most important unmeasured factor is that trade between countries,
    especially when firms are splitting up the value chain of
    production, often involves a transfer of knowledge that can involve
    skills in production, technology, management, finance, and law.

Low-income countries benefit more from trade than high-income countries
do. In some ways, the giant U.S. economy has less need for international
trade, because it can already take advantage of internal trade within
its economy. However, many smaller national economies around the world,
in regions like Latin America, Africa, the Middle East, and Asia, have
much more limited possibilities for trade inside their countries or
their immediate regions. Without international trade, they may have
little ability to benefit from comparative advantage, slicing up the
value chain, or economies of scale. Moreover, smaller economies often
have fewer competitive firms making goods within their economy, and thus
firms have less pressure from other firms to provide the goods and
prices that consumers want.

The economic gains from expanding international trade are measured in
hundreds of billions of dollars, and the gains from international trade
as a whole probably reach well into the trillions of dollars. The
potential for gains from trade may be especially high among the smaller
and lower-income countries of the world.

### Link It Up {#link-it-up .Heading3Grey}

Visit this [website](http://openstax.org/l/tradebenefits) for a list of
some benefits of trade.

### From Interpersonal to International Trade

Most people find it easy to believe that they, personally, would not be
better off if they tried to grow and process all of their own food, to
make all of their own clothes, to build their own cars and houses from
scratch, and so on. Instead, we all benefit from living in economies
where people and firms can specialize and trade with each other.

The benefits of trade do not stop at national boundaries, either.
Earlier we explained that the division of labor could increase output
for three reasons: (1) workers with different characteristics can
specialize in the types of production where they have a comparative
advantage; (2) firms and workers who specialize in a certain product
become more productive with learning and practice; and (3) economies of
scale. These three reasons apply from the individual and community level
right up to the international level. If it makes sense to you that
interpersonal, intercommunity, and interstate trade offer economic
gains, it should make sense that international trade offers gains, too.

International trade currently involves about \$20 trillion worth of
goods and services moving around the globe. Any economic force of that
size, even if it confers overall benefits, is certain to cause
disruption and controversy. This chapter has only made the case that
trade brings economic benefits. Other chapters discuss, in detail, the
public policy arguments over whether to restrict international trade.

### Bring It Home {#bring-it-home .Heading3Grey}

#### Just Whose iPhone Is It? {#just-whose-iphone-is-it .Heading4Grey}

Apple Corporation uses a global platform to produce the iPhone. Now that
you understand the concept of comparative advantage, you can see why the
engineering and design of the iPhone is done in the United States. The
United States has built up a comparative advantage over the years in
designing and marketing products, and sacrifices fewer resources to
design high-tech devices relative to other countries. China has a
comparative advantage in assembling the phone due to its large skilled
labor force. Korea has a comparative advantage in producing components.
Korea focuses its production by increasing its scale, learning better
ways to produce screens and computer chips, and uses innovation to lower
average costs of production. Apple, in turn, benefits because it can
purchase these quality products at lower prices. Put the global assembly
line together and you have the device with which we are all so familiar.
