## 20.2 International Trade and Its Effects on Jobs, Wages, and Working Conditions

### Learning Objectives

By the end of this section, you will be able to:

-   Discuss how international trade influences the job market
-   Analyze the opportunity cost of protectionism
-   Explain how international trade impacts wages, labor standards, and
    working conditions

In theory at least, imports might injure workers in several different
ways: fewer jobs, lower wages, or poor working conditions. Let's
consider these in turn.

### Fewer Jobs?

In the early 1990s, the United States was negotiating the North American
Free Trade Agreement (NAFTA)[1](#fs-idm352845312) with Mexico, an
agreement that reduced tariffs, import quotas, and nontariff barriers to
trade between the United States, Mexico, and Canada. H. Ross Perot, a
1992 candidate for U.S. president, claimed, in prominent campaign
arguments, that if the United States expanded trade with Mexico, there
would be a "giant sucking sound" as U.S. employers relocated to Mexico
to take advantage of lower wages. After all, average wages in Mexico
were, at that time, about one-eighth of those in the United States.
NAFTA passed Congress, President Bill Clinton signed it into law, and it
took effect in 1995. For the next six years, the United States economy
had some of the most rapid job growth and low unemployment in its
history. Those who feared that open trade with Mexico would lead to a
dramatic decrease in jobs were proven wrong.

1

As of July 1, 2020, NAFTA was officially replaced with the United
States-Mexico-Canada (USMCA) free trade agreement. It is broadly similar
to the original NAFTA.

This result was no surprise to economists. After all, the trend toward
globalization has been going on for decades, not just since NAFTA. If
trade reduced the number of available jobs, then the United States
should have been seeing a steady loss of jobs for decades. While the
United States economy does experience rises and falls in unemployment
rates, the number of jobs is not falling over extended periods of time.
The number of U.S. jobs rose from 71 million in 1970 to 150 million in
2021.

Protectionism certainly saves jobs in the specific industry being
protected but, for two reasons, it costs jobs in other unprotected
industries. First, if consumers are paying higher prices to the
protected industry, they inevitably have less money to spend on goods
from other industries, and so jobs are lost in those other industries.
Second, if a firm sells the protected product to other firms, so that
other firms must now pay a higher price for a key input, then those
firms will lose sales to foreign producers who do not need to pay the
higher price. Lost sales translate into lost jobs. The hidden
opportunity cost of using protectionism to save jobs in one industry is
jobs sacrificed in other industries. This is why the United States
International Trade Commission, in its study of barriers to trade,
predicts that reducing trade barriers would not lead to an overall loss
of jobs. Protectionism reshuffles jobs from industries without import
protections to industries that are protected from imports, but it does
not create more jobs.

Moreover, the costs of saving jobs through protectionism can be very
high. A number of different studies have attempted to estimate the cost
to consumers in higher prices per job saved through protectionism.
[Table 20.2](#Table_34_02) shows a sample of results, compiled by
economists at the Federal Reserve Bank of Dallas. Saving a job through
protectionism typically costs much more than the actual worker's salary.
For example, a study published in 2002 compiled evidence that using
protectionism to save an average job in the textile and apparel industry
would cost \$199,000 per job saved. In other words, those workers could
have been paid \$100,000 per year to be unemployed and the cost would
only be half of what it is to keep them working in the textile and
apparel industry. This result is not unique to textiles and apparel.

Table 20.2 Cost to U.S. Consumers of Saving a Job through Protectionism
(Source: Federal Reserve Bank of Dallas)

Why does it cost so much to save jobs through protectionism? The basic
reason is that not all of the extra money that consumers pay because of
tariffs or quotas goes to save jobs. For example, if the government
imposes tariffs on steel imports so that steel buyers pay a higher
price, U.S. steel companies earn greater profits, buy more equipment,
pay bigger bonuses to managers, give pay raises to existing
employees---and also avoid firing some additional workers. Only part of
the higher price of protected steel goes toward saving jobs. Also, when
an industry is protected, the economy as a whole loses the benefits of
playing to its comparative advantage---in other words, producing what it
is best at. Therefore, part of the higher price that consumers pay for
protected goods is lost economic efficiency, which we can measure as
another deadweight loss, like what we discussed in [Labor and Financial
Markets](http://openstax.org/books/principles-microeconomics-3e/pages/4-introduction-to-labor-and-financial-markets).

There's a bumper sticker that speaks to the threat some U.S. workers
feel from imported products: "Buy American---Save U.S. Jobs." If an
economist were driving the car, the sticker might declare: "Block
Imports---Save Jobs for Some Americans, Lose Jobs for Other Americans,
and Also Pay High Prices."

### Trade and Wages

Even if trade does not reduce the number of jobs, it could affect wages.
Here, it is important to separate issues about the average level of
wages from issues about whether the wages of certain workers may be
helped or hurt by trade.

Because trade raises the amount that an economy can produce by letting
firms and workers play to their comparative advantage, trade will also
cause the average level of wages in an economy to rise. Workers who can
produce more will be more desirable to employers, which will shift the
demand for their labor out to the right, and increase wages in the labor
market. By contrast, barriers to trade will reduce the average level of
wages in an economy.

However, even if trade increases the overall wage level, it will still
benefit some workers and hurt others. Workers in industries that are
confronted by competition from imported products may find that demand
for their labor decreases and shifts back to the left, so that their
wages decline with a rise in international trade. Conversely, workers in
industries that benefit from selling in global markets may find that
demand for their labor shifts out to the right, so that trade raises
their wages.

### Link It Up {#link-it-up .Heading3Grey}

View this [website](http://openstax.org/l/fairtradecoffee) to read an
article on the issues surrounding fair trade coffee.

One concern is that while globalization may be benefiting high-skilled,
high-wage workers in the United States, it may also impose costs on
low-skilled, low-wage workers. After all, high-skilled U.S. workers
presumably benefit from increased sales of sophisticated products like
computers, machinery, and pharmaceuticals in which the United States has
a comparative advantage. Meanwhile, low-skilled U.S. workers must now
compete against extremely low-wage workers worldwide for making simpler
products like toys and clothing. As a result, the wages of low-skilled
U.S. workers are likely to fall. There are, however, a number of reasons
to believe that while globalization has helped some U.S. industries and
hurt others, it has not focused its negative impact on the wages of
low-skilled Americans. First, about half of U.S. trade is intra-industry
trade. That means the U.S. trades similar goods with other high-wage
economies like Canada, Japan, Germany, and the United Kingdom. For
instance, in 2014 the U.S. exported over 2 million cars, from all the
major automakers, and also imported several million cars from other
countries.

Most U.S. workers in these industries have above-average skills and
wages---and many of them do quite well in the world of globalization.
Some evidence suggested that intra-industry trade between similar
countries had a small impact on domestic workers but later evidence
indicates that it all depends on how flexible the labor market is. In
other words, the key is how flexible workers are in finding jobs in
different industries. The effect of trade on low-wage workers depends
considerably on the structure of labor markets and indirect effects felt
in other parts of the economy. For example, in the United States and the
United Kingdom, because labor market frictions are low, the impact of
trade on low income workers is small.

Second, many low-skilled U.S. workers hold service jobs that imports
from low-wage countries cannot replace. For example, we cannot import
lawn care services or moving and hauling services or hotel maids from
countries long distances away like China or Bangladesh. Competition from
imported products is not the primary determinant of their wages.

Finally, while the focus of the discussion here is on wages, it is worth
pointing out that low-wage U.S. workers suffer due to protectionism in
all the industries---even those in which they do not work. For example,
food and clothing are protected industries. These low-wage workers
therefore pay higher prices for these basic necessities and as such
their dollar stretches over fewer goods.

The benefits and costs of increased trade in terms of its effect on
wages are not distributed evenly across the economy. However, the growth
of international trade has helped to raise the productivity of U.S.
workers as a whole---and thus helped to raise the average level of
wages.

### Labor Standards and Working Conditions

Workers in many low-income countries around the world labor under
conditions that would be illegal for a worker in the United States.
Workers in countries like China, Thailand, Brazil, South Africa, and
Poland are often paid less than the United States minimum wage. For
example, in the United States, the national minimum wage is \$7.25 per
hour. A typical wage in many low-income countries might be more like
\$7.25 per day, or often much less. Moreover, working conditions in
low-income countries may be extremely unpleasant, or even unsafe. In the
worst cases, production may involve the child labor or even workers who
are mistreated, abused, or entrapped in their jobs. These concerns over
foreign labor standards do not affect most of U.S. trade, which is
intra-industry and carried out with other high-income countries that
have labor standards similar to the United States, but it is,
nonetheless, morally and economically important.

In thinking about labor standards in other countries, it is important to
draw some distinctions between what is truly unacceptable and what is
painful to think about. Most people, economists included, have little
difficulty with the idea that production by six-year-olds confined in
factories, by people who are abused or mistreated, or by slave labor is
morally unacceptable. They would support aggressive efforts to eliminate
such practices---including shutting out imported products made with such
labor. Many cases, however, are less clear-cut. An opinion article in
the *New York Times* several years ago described the case of Ahmed Zia,
a 14-year-old boy from Pakistan. He earned \$2 per day working in a
carpet factory. He dropped out of school in second grade. Should the
United States and other countries refuse to purchase rugs made by Ahmed
and his co-workers? If the carpet factories were to close, the likely
alternative job for Ahmed is farm work, and as Ahmed says of his
carpet-weaving job: "This makes much more money and is more
comfortable."

Other workers may have even less attractive alternative jobs, perhaps
scavenging garbage or prostitution. The real problem for Ahmed and many
others in low-income countries is not that globalization has made their
lives worse, but rather that they have so few good life alternatives.
The United States went through similar situations during the nineteenth
and early twentieth centuries.

In closing, there is some irony when the United States government or
U.S. citizens take issue with labor standards in low-income countries,
because the United States is not a world leader in government laws to
protect employees. According to a recent study by the Organization for
Economic Cooperation and Development (OECD), the U.S. is the only one of
41 countries that does not provide mandated paid leave for new parents,
and among the 40 countries that do mandate paid leave, the minimum
duration is about two months. Many European workers receive six weeks or
more of paid vacation per year. In the United States, vacations are
often one to three weeks per year. If European countries accused the
United States of using unfair labor standards to make U.S. products
cheaply, and announced that they would shut out all U.S. imports until
the United States adopted paid parental leave, added more national
holidays, and doubled vacation time, Americans would be outraged. Yet
when U.S. protectionists start talking about restricting imports from
poor countries because of low wage levels and poor working conditions,
they are making a very similar argument. This is not to say that labor
conditions in low-income countries are not an important issue. They are.
However, linking labor conditions in low-income countries to trade
deflects the emphasis from the real question to ask: "What are
acceptable and enforceable minimum labor standards and protections to
have the world over?"
