## 7.1 Explicit and Implicit Costs, and Accounting and Economic Profit

### Learning Objectives

By the end of this section, you will be able to:

-   Explain the difference between explicit costs and implicit costs
-   Understand the relationship between cost and revenue

Each business, regardless of size or complexity, tries to earn a profit:

$\text{Profit} = \text{Total~Revenue\ –\ Total~Cost}$

Total revenue is the income the firm generates from selling its
products. We calculate it by multiplying the price of the product times
the quantity of output sold:

$\text{Total~Revenue} = \text{Price\ ×\ Quantity}$

We will see in the following chapters that revenue is a function of the
demand for the firm's products.

Total cost is what the firm pays for producing and selling its products.
Recall that production involves the firm converting inputs to outputs.
Each of those inputs has a cost to the firm. The sum of all those costs
is total cost. We will learn in this chapter that short run costs are
different from long run costs.

We can distinguish between two types of cost: explicit and implicit.
Explicit costs are out-of-pocket costs, that is, actual payments. Wages
that a firm pays its employees or rent that a firm pays for its office
are explicit costs. Implicit costs are more subtle, but just as
important. They represent the opportunity cost of using resources that
the firm already owns. Often for small businesses, they are resources
that the owners contribute. For example, working in the business while
not earning a formal salary, or using the ground floor of a home as a
retail store are both implicit costs. Implicit costs also include the
depreciation of goods, materials, and equipment that are necessary for a
company to operate. (See the Work It Out feature for an extended
example.)

These two definitions of cost are important for distinguishing between
two conceptions of profit, accounting profit, and economic profit.
Accounting profit is a cash concept. It means total revenue minus
explicit costs---the difference between dollars brought in and dollars
paid out. Economic profit is total revenue minus total cost, including
both explicit and implicit costs. The difference is important because
even though a business pays income taxes based on its accounting profit,
whether or not it is economically successful depends on its economic
profit.

### Work It Out {#work-it-out .Heading3Grey}

#### Calculating Implicit Costs {#calculating-implicit-costs .Heading4Grey}

Consider the following example. Eryn currently works for a corporate law
firm. She is considering opening her own legal practice, where she
expects to earn \$200,000 per year once she establishes herself. To run
her own firm, she would need an office and a law clerk. She has found
the perfect office, which rents for \$50,000 per year. She could hire a
law clerk for \$35,000 per year. If these figures are accurate, would
Eryn's legal practice be profitable?

Step 1. First you have to calculate the costs. You can take what you
know about explicit costs and total them:

![multiline equation row 1 Office rental colon dollar sign 50,000 row 2
Law clerk prime s salary colon plus dollar sign 35,000 bar bar bar bar
bar bar bar bar bar bar bar bar row 3 Total explicit costs colon dollar
sign 85,000](media/rId29.png){width="2.21875in"
height="0.7291666666666666in"}

Step 2. Subtracting the explicit costs from the revenue gives you the
accounting profit.

![multiline equation row 1 Revenues colon dollar sign 200,000 row 2
Explicit costs colon en dash dollar sign 85,000 bar bar bar bar bar bar
bar bar bar bar bar bar row 3 Accounting profit colon dollar sign
115,000](media/rId31.png){width="2.1354166666666665in"
height="0.7291666666666666in"}

However, these calculations consider only the explicit costs. To open
her own practice, Eryn would have to quit her current job, where she is
earning an annual salary of \$125,000. This would be an implicit cost of
opening her own firm.

Step 3. You need to subtract both the explicit and implicit costs to
determine the true economic profit:

![multiline equation row 1 Economic profit equals total revenues en dash
explicit costs en dash implicit costs row 2 Blank equals dollar sign
200,000 en dash dollar sign 85,000 en dash dollar sign 125,000 row 3
Blank equals en dash dollar sign 10,000 per
year](media/rId33.png){width="4.375in" height="0.6145833333333334in"}

Eryn would be losing \$10,000 per year. That does not mean she would not
want to open her own business, but it does mean she would be earning
\$10,000 less than if she worked for the corporate firm.

Implicit costs can include other things as well. Maybe Eryn values her
leisure time, and starting her own firm would require her to put in more
hours than at the corporate firm. In this case, the lost leisure would
also be an implicit cost that would subtract from economic profits.

Now that we have an idea about the different types of costs, let's look
at cost structures. A firm's cost structure in the long run may be
different from that in the short run. We turn to that distinction in the
next few sections.
