project:
  type: book
  output-dir: ../HTML_open_principles_of_microeconomics


  
book:
  title: "Open Principles of Microeconomics"
  author: "Justin Johnson"
  date: "2023-10-10"
  page-navigation: true


  chapters: 
  - index.qmd
  - 01_introduction.qmd
  - 02_choice_with_scarcity.qmd
  - 03_demand_and_supply.qmd
  - 04_labor_markets.qmd
  - 05_elasticity.qmd
  - 06_consumer_choice.qmd
  - 07_production_and_costs.qmd
  - 08_perfect_competition.qmd
  - 09_monopoly.qmd
  - 10_market_spectrum.qmd
  - 11_antitrust.qmd
  - 12_negative_externalities.qmd
  - 13_positive_externalities.qmd
  - 14_labor_and_income.qmd
  - 15_poverty_and_inequality.qmd
  - 16_information_and_risk.qmd
  - 17_financial_markets.qmd
  - 18_public_economy.qmd
  - 19_international_trade.qmd
  - 20_globalization.qmd
  appendices: 
  - a1_math_in_econ.qmd
  - a2_indifference_curves.qmd
  - a3_present_discounted_value.qmd
  - a4_generating_supply_and_demand_curves.qmd

format:
  html:
    theme: yeti
    number-sections: false

    code-fold: true
    code-tools: true
    
  # revealjs: 
  #   theme: cosmo
  pdf:
    documentclass: scrreprt
    toc: true
    toc-depth: 2
    number-sections: false



