project:
  type: book
  output-dir: ../RENDERED_open_principles_of_microeconomics

book:
  title: "Open Principles of Microeconomics"
  author: "Justin Johnson"
  date: "2023-10-10"
  page-navigation: true

  chapters: 
  - index.qmd
    

  - part: Welcome to Economics!
    chapters:       
      - 1-introduction.qmd
      - 1-1-what-is-economics-and-why-is-it-important.qmd
      - 1-3-how-economists-use-theories-and-models-to-understand-economic-issues.qmd
  - part: Choice in a World of Scarcity
    chapters:
      - 2-introduction-to-choice-in-a-world-of-scarcity.qmd



execute:
  freeze: true
  cache: true

format:
  html:
    theme: cosmo
  # revealjs: 
  #   theme: cosmo
  # pdf:
  #   documentclass: scrreprt



