project:
  type: book
  output-dir: ../HTML_open_principles_of_microeconomics


book:
  title: "Open Principles of Microeconomics"
  author: "Justin Johnson"
  date: "2023-10-10"
  page-navigation: true


  chapters: 
  - index.qmd
  - chapter1.qmd
  - chapter2.qmd
  - chapter3.qmd
  - chapter4.qmd
  - chapter5.qmd
  - chapter6.qmd
  - chapter7.qmd
  - chapter8.qmd
  - chapter9.qmd
  - chapter10.qmd
  - chapter11.qmd
  - chapter12.qmd
  - chapter13.qmd
  - chapter14.qmd
  - chapter15.qmd
  - chapter16.qmd
  - chapter17.qmd
  - chapter18.qmd
  - chapter19.qmd
  - chapter20.qmd
  appendices: 
  - a-the-use-of-mathematics-in-principles-of-economics.qmd
  - b-indifference-curves.qmd
  - c-present-discounted-value.qmd

    
execute:
  freeze: true
  cache: true

format:
  html:
    theme: yeti
    number-sections: false

    code-fold: true
    code-tools: true
    
  # revealjs: 
  #   theme: cosmo
  pdf:
    documentclass: scrreprt
    toc: true
    toc-depth: 2
    number-sections: false



