project:
  type: book
  output-dir: ../HTML_open_principles_of_microeconomics


book:
  title: "Open Principles of Microeconomics"
  author: "Justin Johnson"
  date: "2023-10-10"
  page-navigation: true


  chapters: 
  - index.qmd



  - part: 1-Welcome to Economics!
    chapters:
      - 1-introduction.qmd
      - 1-1-what-is-economics-and-why-is-it-important.qmd
      - 1-2-microeconomics-and-macroeconomics.qmd
      - 1-3-how-economists-use-theories-and-models-to-understand-economic-issues.qmd
      - 1-4-how-to-organize-economies-an-overview-of-economic-systems.qmd

  - part: 2-Choice in a World of Scarcity
    chapters:
      - 2-introduction-to-choice-in-a-world-of-scarcity.qmd
      - 2-1-how-individuals-make-choices-based-on-their-budget-constraint.qmd
      - 2-2-the-production-possibilities-frontier-and-social-choices.qmd
      - 2-3-confronting-objections-to-the-economic-approach.qmd

  - part: 3-Demand and Supply
    chapters:
      - 3-introduction-to-demand-and-supply.qmd
      - 3-1-demand-supply-and-equilibrium-in-markets-for-goods-and-services.qmd
      - 3-2-shifts-in-demand-and-supply-for-goods-and-services.qmd
      - 3-3-changes-in-equilibrium-price-and-quantity-the-four-step-process.qmd
      - 3-4-price-ceilings-and-price-floors.qmd
      - 3-5-demand-supply-and-efficiency.qmd

  - part: 4-Labor and Financial Markets
    chapters:
      - 4-introduction-to-labor-and-financial-markets.qmd
      - 4-1-demand-and-supply-at-work-in-labor-markets.qmd
      - 4-2-demand-and-supply-in-financial-markets.qmd
      - 4-3-the-market-system-as-an-efficient-mechanism-for-information.qmd

  - part: 5-Elasticity
    chapters:
      - 5-introduction-to-elasticity.qmd
      - 5-1-price-elasticity-of-demand-and-price-elasticity-of-supply.qmd
      - 5-2-polar-cases-of-elasticity-and-constant-elasticity.qmd
      - 5-3-elasticity-and-pricing.qmd
      - 5-4-elasticity-in-areas-other-than-price.qmd

  - part: 6-Consumer Choices
    chapters:
      - 6-introduction-to-consumer-choices.qmd
      - 6-1-consumption-choices.qmd
      - 6-2-how-changes-in-income-and-prices-affect-consumption-choices.qmd
      - 6-3-behavioral-economics-an-alternative-framework-for-consumer-choice.qmd

  - part: 7-Production, Costs, and Industry Structure
    chapters:
      - 7-introduction-to-production-costs-and-industry-structure.qmd
      - 7-1-explicit-and-implicit-costs-and-accounting-and-economic-profit.qmd
      - 7-2-production-in-the-short-run.qmd
      - 7-3-costs-in-the-short-run.qmd
      - 7-4-production-in-the-long-run.qmd
      - 7-5-costs-in-the-long-run.qmd

  - part: 8-Perfect Competition
    chapters:
      - 8-introduction-to-perfect-competition.qmd
      - 8-1-perfect-competition-and-why-it-matters.qmd
      - 8-2-how-perfectly-competitive-firms-make-output-decisions.qmd
      - 8-3-entry-and-exit-decisions-in-the-long-run.qmd
      - 8-4-efficiency-in-perfectly-competitive-markets.qmd

  - part: 9-Monopoly
    chapters:
      - 9-introduction-to-a-monopoly.qmd
      - 9-1-how-monopolies-form-barriers-to-entry.qmd
      - 9-2-how-a-profit-maximizing-monopoly-chooses-output-and-price.qmd

  - part: 10-Monopolistic Competition and Oligopoly
    chapters:
      - 10-introduction-to-monopolistic-competition-and-oligopoly.qmd
      - 10-1-monopolistic-competition.qmd
      - 10-2-oligopoly.qmd

  - part: 11-Monopoly and Antitrust Policy
    chapters:
      - 11-introduction-to-monopoly-and-antitrust-policy.qmd
      - 11-1-corporate-mergers.qmd
      - 11-2-regulating-anticompetitive-behavior.qmd
      - 11-3-regulating-natural-monopolies.qmd
      - 11-4-the-great-deregulation-experiment.qmd

  - part: 12-Environmental Protection and Negative Externalities
    chapters:
      - 12-introduction-to-environmental-protection-and-negative-externalities.qmd
      - 12-1-the-economics-of-pollution.qmd
      - 12-2-command-and-control-regulation.qmd
      - 12-3-market-oriented-environmental-tools.qmd
      - 12-4-the-benefits-and-costs-of-u-s-environmental-laws.qmd
      - 12-5-international-environmental-issues.qmd
      - 12-6-the-tradeoff-between-economic-output-and-environmental-protection.qmd

  - part: 13-Positive Externalities and Public Goods
    chapters:
      - 13-introduction-to-positive-externalities-and-public-goods.qmd
      - 13-1-investments-in-innovation.qmd
      - 13-2-how-governments-can-encourage-innovation.qmd
      - 13-3-public-goods.qmd

  - part: 14-Labor Markets and Income
    chapters:
      - 14-introduction-to-labor-markets-and-income.qmd
      - 14-1-the-theory-of-labor-markets.qmd
      - 14-2-wages-and-employment-in-an-imperfectly-competitive-labor-market.qmd
      - 14-3-market-power-on-the-supply-side-of-labor-markets-unions.qmd
      - 14-4-bilateral-monopoly.qmd
      - 14-5-employment-discrimination.qmd
      - 14-6-immigration.qmd

  - part: 15-Poverty and Economic Inequality
    chapters:
      - 15-introduction-to-poverty-and-economic-inequality.qmd
      - 15-1-drawing-the-poverty-line.qmd
      - 15-2-the-poverty-trap.qmd
      - 15-3-the-safety-net.qmd
      - 15-4-income-inequality-measurement-and-causes.qmd
      - 15-5-government-policies-to-reduce-income-inequality.qmd

  - part: 16-Information, Risk, and Insurance
    chapters:
      - 16-introduction-to-information-risk-and-insurance.qmd
      - 16-1-the-problem-of-imperfect-information-and-asymmetric-information.qmd
      - 16-2-insurance-and-imperfect-information.qmd

  - part: 17-Financial Markets
    chapters:
      - 17-introduction-to-financial-markets.qmd
      - 17-1-how-businesses-raise-financial-capital.qmd
      - 17-2-how-households-supply-financial-capital.qmd
      - 17-3-how-to-accumulate-personal-wealth.qmd

  - part: 18-Public Economy
    chapters:
      - 18-introduction-to-public-economy.qmd
      - 18-1-voter-participation-and-costs-of-elections.qmd
      - 18-2-special-interest-politics.qmd
      - 18-3-flaws-in-the-democratic-system-of-government.qmd

  - part: 19-International Trade
    chapters:
      - 19-introduction-to-international-trade.qmd
      - 19-1-absolute-and-comparative-advantage.qmd
      - 19-2-what-happens-when-a-country-has-an-absolute-advantage-in-all-goods.qmd
      - 19-3-intra-industry-trade-between-similar-economies.qmd
      - 19-4-the-benefits-of-reducing-barriers-to-international-trade.qmd

  - part: 20-Globalization and Protectionism
    chapters:
      - 20-introduction-to-globalization-and-protectionism.qmd
      - 20-1-protectionism-an-indirect-subsidy-from-consumers-to-producers.qmd
      - 20-2-international-trade-and-its-effects-on-jobs-wages-and-working-conditions.qmd
      - 20-3-arguments-in-support-of-restricting-imports.qmd
      - 20-4-how-governments-enact-trade-policy-globally-regionally-and-nationally.qmd
      - 20-5-the-tradeoffs-of-trade-policy.qmd




execute:
  freeze: true
  cache: true

format:
  html:
    theme: yeti
    number-sections: false

    code-fold: true
    code-tools: true
    
  # revealjs: 
  #   theme: cosmo
  pdf:
    documentclass: scrreprt



