"""
Headless checks that every interactive app in the book must pass. The harness
lives in interactive_textbook_pipeline; this file only lists the apps, each
with one representative non-default state that touches every key type the app
supports (a slider, a toggle, a nudge).

Run:  python -m pytest tests/ -q
One:  python -m pytest tests/ -q -k supply
"""
import pathlib

from interactive_textbook_pipeline.apptest import app_tests, browser  # noqa: F401

APPS_DIR = pathlib.Path(__file__).resolve().parent.parent / "open_principles_of_microeconomics" / "apps"

# name -> a state string using every key type the app has
APPS = {
    "supply_shifts_textbook": "v=1&@pt.J=0,-20&dq_s1=-2&p=22000&show_s1=0",
    "budget_constraint_textbook": "v=1&@pt.C=0,-20&lbl_x=Trips&m=14&sel=C&show_shading=0",
    "equilibrium_textbook": "v=1&@pt.E=0,-20&dq_d=40&p=1.2&show_brackets=0",
    "comparative_advantage_textbook": "v=1&@pt.br.A=0,-20&max_wheat_us=80&show_shading=0",
    "ppf_textbook": "v=1&@pt.B=0,-20&lbl_x=Schools&max_education=150&sel=B&show_shading=0",
    "efficiency_ppf_textbook": "v=1&@pt.R=0,-20&lbl_y=Clinics&r_education=40&sel=R&show_gain=0",
    "demand_curve_textbook": "v=1&@an.2=10,0&dq_d=40&sel=2&show_annot=0",
    "supply_curve_textbook": "v=1&@an.2=10,0&dq_s=40&sel=2&show_annot=0",
    "demand_basic_textbook": "v=1&@an.P0=0,-10&n_d=1.5&show_arrows=0&t=0.6",
    "demand_two_points_textbook": "v=1&@an.Q1=0,10&show_arrows=0&t0=0.3&t1=0.7",
    "demand_shifts_textbook": "v=1&@pt.Q=0,-20&dq_d1=4&p=24000&show_d2=0",
    "demand_shift_dd_textbook": "v=1&@an.Q1=0,10&dq_d1=25&show_arrows=0&t=0.6",
    "demand_shift_factors_textbook": "v=1&@d0.a=0,-10&dq_d1=40&show_arrows=0",
    "individual_vs_social_textbook": "v=1&@x.soc=0,-10&max_g1_ind=120&n_ppf=1&show_shading=0",
    "market_shifts_textbook": "v=1&@pt.a.E1=0,-20&dp_s1=0.3&n_d=1.5&show_arrows=0",
    "circular_flow_textbook": "v=1&@box.hh=0,-20&@flow.A=10,0&gap_x=250&show_fm=0&show_markets=1",
    "supply_cost_shift_textbook": "v=1&@an.P0=0,-10&dp_s=1&q=5&show_s1=0",
    "supply_shift_factors_textbook": "v=1&@s0.a=0,-10&dq_s1=30&show_arrows=0",
    "four_step_salmon_textbook": "v=1&@an.E0=0,-10&dq_s1=50&show_arrows=0",
    "four_step_print_news_textbook": "v=1&@pt.E0=0,-10&dq_d1=-2.5&show_arrows=0",
    "four_step_postal_textbook": "v=1&@pt.a.E0=0,-10&dq_s1=-2.5&show_arrows=0",
    "four_step_postal_combined_textbook": "v=1&@pt.E3=0,-10&dq_d1=-1&show_arrows=0",
    "shift_vs_movement_textbook": "v=1&@an.shift1=0,-10&dq_s2=2&show_shift3=0",
    "price_ceiling_textbook": "v=1&@an.shortage=0,-10&p=450&show_grid=0",
    "price_floor_textbook": "v=1&@an.surplus=0,-10&p=5&show_annot=0",
    "surplus_textbook": "v=1&@an.F=0,-10&dq_d=4&show_shading=1",
    "surplus_price_controls_textbook": "v=1&@an.a.T=0,-10&p_ceiling=300&show_shading=1",
    "labor_market_nurses_textbook": "v=1&@an.surplus=0,-10&p_above=95000&show_grid=0",
    "labor_tech_shifts_textbook": "v=1&@pt.a.E0=0,-10&dq_d1_low=-1.5&show_arrows=0",
    "living_wage_textbook": "v=1&@an.surplus=0,-10&p=13&show_grid=0",
    "financial_market_credit_textbook": "v=1&@an.shortage=0,10&p_below=12&show_grid=0",
    "global_borrower_textbook": "v=1&@pt.E0=0,-10&dq_s1=-1&show_arrows=0",
    "credit_price_ceiling_textbook": "v=1&@an.shortage=0,10&p=2.4&show_annot=0",
    "generic_market_textbook": "v=1&@pt.E=0,-10&dq_d=1&show_eqlines=0",
    "nurses_2030_textbook": "v=1&@pt.E0=0,-10&dq_d1=1&show_arrows=0",
    "elasticity_demand_textbook": "v=1&@pt.A=0,-10&dq_d=100&sel=B&show_braces=0",
    "elasticity_supply_textbook": "v=1&@pt.B=10,0&p=800&show_grid=0",
    "polar_elasticity_textbook": "v=1&@d.a=0,-10&p=6&show_vertical=1",
    "unitary_demand_textbook": "v=1&@pt.A=0,-10&rev=240&show_pct=0",
    "unitary_supply_textbook": "v=1&@pt.D=0,-10&q=60&show_pct=0",
    "elasticity_pass_through_textbook": "v=1&@pt.a.E0=0,-10&dq_s1=-2&show_arrows=0",
    "tax_incidence_textbook": "v=1&@pt.a.E=0,-10&show_revenue=0&tax=3",
    "oil_shock_textbook": "v=1&@pt.a.E0=0,-10&dq_s1=-2.5&show_arrows=0",
    "jose_budget_textbook": "v=1&@pt.S=0,-10&income=42&show_utility=1",
    "income_change_textbook": "v=1&@pt.N=0,-10&income=1500&show_arrows=0",
    "price_change_textbook": "v=1&@pt.K=0,10&ratio=1.5&show_arrows=0",
    "demand_derivation_textbook": "v=1&@pt.a.M0=0,-10&elas=2&show_annot=0",
    "education_earnings_textbook": "v=1&@lg=0,-20&bar_h=14&show_nat=1",
    "competition_spectrum_textbook": "v=1&@col.pc=0,-10&spread=70&show_firms=0",
    "lumberjacks_product_textbook": "v=1&@ttl.a=0,-10&mp2=4&show_points=1",
    "tp_mp_general_textbook": "v=1&@x.a=0,-10&l0=5&show_peak=1",
    "total_cost_clip_joint_textbook": "v=1&@an.fc=10,0&fc=200&show_brace=0",
    "cost_curves_clip_joint_textbook": "v=1&@mc=0,-10&wage=120&show_avc=0",
    "economies_of_scale_textbook": "v=1&@pt.M=0,-10&q=4000&show_probe=1",
    "srac_lrac_textbook": "v=1&@lrac=0,-10&s=2&show_regions=0",
    "lrac_shapes_textbook": "v=1&@pt.a.R=0,-10&width=7500&show_dots=0",
    "raspberry_totals_textbook": "v=1&@tc=0,-10&price=5&show_zones=0",
    "raspberry_marginal_textbook": "v=1&@mc=0,-10&price=6&show_points=0",
    "raspberry_market_textbook": "v=1&@d=0,-10&dq=200&show_dashed=0",
    "profit_loss_ac_textbook": "v=1&@ac.a=0,-10&p_a=6&show_shade=0",
    "shutdown_avc_textbook": "v=1&@mc.a=0,-10&p_a=2.5&show_q=1",
    "profit_loss_shutdown_textbook": "v=1&@an.be=0,-10&fc=4&show_zones=0",
    "lrs_industry_textbook": "v=1&@lrs.a=0,-10&dd=4&show_lrs=0",
    "natural_monopoly_textbook": "v=1&@lrac=0,-10&market=1.8&show_dashed=0",
    "perceived_demand_textbook": "v=1&@pt.S=0,-10&q_l=1.5&show_dashed=0",
    "healthpill_totals_textbook": "v=1&@tc=0,-10&a=1400&show_points=0",
    "healthpill_marginal_textbook": "v=1&@mc=0,-10&a=1400&show_points=0",
    "monopoly_profit_boxes_textbook": "v=1&@ac=0,-10&a=1100&show_boxes=0",
    "monopoly_three_steps_textbook": "v=1&@pt.R=0,-10&a=11&show_steps=0",
    "mr_below_demand_textbook": "v=1&@d=0,-10&slope=1.4&show_mr=0",
    "three_perceived_demands_textbook": "v=1&@y.b=0,-10&diff=5&show_captions=0",
    "pizza_profit_textbook": "v=1&@mc=0,-10&dp=-3&show_boxes=0",
    "entry_exit_textbook": "v=1&@pt.T=0,-10&shift=2&show_arrows=0",
    "kinked_demand_textbook": "v=1&@pt.kink=0,-10&p_cut=200&show_coords=0",
    "merger_review_textbook": "v=1&@y.a=0,-10&from=2003&show_big=1",
    "natural_monopoly_regulation_textbook": "v=1&@pt.A=0,-10&choice=4&show_pick=1",
    "pollution_supply_shift_textbook": "v=1&@pt.E0=0,-10&cost=200&show_social=0",
    "pollution_charge_textbook": "v=1&@mc=0,-10&charge=1750&show_stop=1",
    "protection_costs_benefits_textbook": "v=1&@mc=0,-10&spread=1.4&show_lines=0",
    "output_environment_ppf_textbook": "v=1&@pt.Q=0,-10&waste=1&show_m=0",
    "innovation_capital_textbook": "v=1&@dp=0,-10&rate=4&show_social=0",
    "flu_shots_subsidy_textbook": "v=1&@an.sub=0,-10&spill=1.5&show_brace=0",
    "patents_filed_granted_textbook": "v=1&@lg=0,-10&from=2005&show_granted=0",
    "labor_marginal_product_textbook": "v=1&@x=0,-10&measure=2&show_dashed=0",
    "labor_demand_equilibrium_textbook": "v=1&@s=0,-10&wage=12&show_mrp=1",
    "market_wage_textbook": "v=1&@s=0,-10&dq=1&show_dashed=0",
    "monopsony_textbook": "v=1&@mc=0,-10&demand=14&show_demand=1",
    "union_wage_floor_textbook": "v=1&@s=0,-10&premium=4&show_union=0",
    "bilateral_monopoly_textbook": "v=1&@mc=0,-10&demand=14&show_brace=1",
    "union_membership_textbook": "v=1&@x=0,-10&from=1970&show_peak=1",
    "employment_by_sector_textbook": "v=1&@lb.0=0,-10&year=2000&show_marks=0",
    "wage_ratios_textbook": "v=1&@lb.0=0,-10&year=2000&show_year=1",
    "population_projection_textbook": "v=1&@lg=0,-10&group=6&show_pick=1",
    "immigration_by_decade_textbook": "v=1&@x=0,-10&decade=1&show_share=1",
    "poverty_rate_textbook": "v=1&@x=0,-10&point=11&show_mark=1",
    "poverty_trap_textbook": "v=1&@pt.A=0,-10&phaseout=50&show_choices=1",
    "tax_credits_spending_textbook": "v=1&@lb.EITC=0,-10&year=1995&show_year=1",
    "safety_net_spending_textbook": "v=1&@lb.0=0,-10&year=2011&show_year=1",
    "medicaid_shares_textbook": "v=1&@cap.a=0,-10&group=1&show_pick=1",
    "lorenz_curve_textbook": "v=1&@lb.eq=0,-10&cut=40&show_2020=0",
    "high_skilled_wages_textbook": "v=1&@s0=0,-10&dd=0&show_new=0",
    "equality_output_tradeoff_textbook": "v=1&@pt.A=0,-10&spot=2&show_pick=1",
    "insurance_flows_textbook": "v=1&@box=0,-10&premium=2160&show_scaled=1",
    "corporate_profits_textbook": "v=1&@x=0,-10&year=2009&show_year=1",
    "banks_intermediaries_textbook": "v=1&@n.banks=0,-10&spread=34&show_labels=0",
    "cd_rates_textbook": "v=1&@lb.0=0,-10&year=2020&show_year=1",
    "bond_rates_textbook": "v=1&@lb.corp=0,-10&year=2002&show_gap=1",
    "stock_indexes_textbook": "v=1&@lb.sp=0,-10&year=2021&show_dow=0",
    "new_home_prices_textbook": "v=1&@x=0,-10&year=2011&show_year=1",
    "voting_cycle_textbook": "v=1&@f.0=0,-10&alex=0&show_first=1",
    "ppf_saudi_us_textbook": "v=1&@C.a=0,-10&saudi=100&show_guides=1",
    "saudi_gains_from_trade_textbook": "v=1&@C.a=0,-10&price=0.25&show_labels=0",
    "ppf_us_mexico_textbook": "v=1&@A.a=0,-10&us_shift=0&show_dots=0",
    "toaster_oven_scale_textbook": "v=1&@p.S=0,-10&q=150&show_read=1",
    "sugar_trade_two_countries_textbook": "v=1&@E.a=0,-10&open=100&show_braces=0",
    "sugar_gains_from_trade_textbook": "v=1&@np.a=0,-10&price=20&show_labels=0",
    "us_sugar_tariff_textbook": "v=1&@A=0,-10&imports=0&show_surplus=1",
    "slope_intercept_line_textbook": "v=1&@eq=0,-10&m=5&show_points=0",
    "supply_demand_algebra_textbook": "v=1&@lb.d=0,-10&dtop=10&show_guides=0",
    "length_weight_textbook": "v=1&@mk=0,-10&len=36&show_girls=0",
    "altitude_air_density_textbook": "v=1&@ev=0,-10&alt=500&show_read=1",
    "unemployment_rate_textbook": "v=1&@x.a=0,-10&year=2000&show_year=1",
    "age_distribution_pies_textbook": "v=1&@lg=0,-10&pull=24&show_labels=0",
    "population_bars_textbook": "v=1&@y.a=0,-10&count=4&show_values=1",
    "age_distribution_bars_textbook": "v=1&@lg=0,-10&pick=3&show_values=0",
    "unemployment_shape_textbook": "v=1&@cap.a=0,-10&stretch=40&show_dots=0",
    "unemployment_scale_textbook": "v=1&@cap.c=0,-10&top=12&show_dots=0",
    "unemployment_window_textbook": "v=1&@cap.f=0,-10&start=1990&show_dots=0",
    "lillys_indifference_curves_textbook": "v=1&@p.A=0,-10&pick=2&show_names=0",
    "lilly_budget_choice_textbook": "v=1&@p.B=0,-10&budget=80&show_points=0",
    "manuel_natasha_textbook": "v=1&@p.W=0,-10&income=80&show_arrows=0",
    "substitution_income_effects_textbook": "v=1&@p.A=0,-10&price=40&show_effects=0",
    "petunia_labor_supply_textbook": "v=1&@p.A=0,-10&wage=14&show_effects=0",
    "quentin_saving_textbook": "v=1&@p.A=0,-10&ret=10&show_effects=0",
    "effects_steps_textbook": "v=1&@p.A=0,-10&step=5&show_caption=0",
}

TestApp = app_tests(APPS_DIR, APPS)
