<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Open Principles of Microeconomics - 9.2 How a Profit-Maximizing Monopoly Chooses Output and Price</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./10-introduction-to-monopolistic-competition-and-oligopoly.html" rel="next">
<link href="./9-1-how-monopolies-form-barriers-to-entry.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./9-introduction-to-a-monopoly.html">9-Monopoly</a></li><li class="breadcrumb-item"><a href="./9-2-how-a-profit-maximizing-monopoly-chooses-output-and-price.html"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">9.2 How a Profit-Maximizing Monopoly Chooses Output and Price</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Open Principles of Microeconomics</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">1-Welcome to Economics!</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1-introduction.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter Objectives</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1-1-what-is-economics-and-why-is-it-important.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">1.1 What Is Economics, and Why Is It Important?</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1-2-microeconomics-and-macroeconomics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">1.2 Microeconomics and Macroeconomics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1-3-how-economists-use-theories-and-models-to-understand-economic-issues.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">1.3 How Economists Use Theories and Models to Understand Economic Issues</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1-4-how-to-organize-economies-an-overview-of-economic-systems.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">1.4 How To Organize Economies: An Overview of Economic Systems</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">2-Choice in a World of Scarcity</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2-introduction-to-choice-in-a-world-of-scarcity.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter Objectives</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2-1-how-individuals-make-choices-based-on-their-budget-constraint.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">2.1 How Individuals Make Choices Based on Their Budget Constraint</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2-2-the-production-possibilities-frontier-and-social-choices.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">2.2 The Production Possibilities Frontier and Social Choices</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2-3-confronting-objections-to-the-economic-approach.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">2.3 Confronting Objections to the Economic Approach</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
 <span class="menu-text">3-Demand and Supply</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./3-introduction-to-demand-and-supply.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter Objectives</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./3-1-demand-supply-and-equilibrium-in-markets-for-goods-and-services.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">3.1 Demand, Supply, and Equilibrium in Markets for Goods and Services</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./3-2-shifts-in-demand-and-supply-for-goods-and-services.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">3.2 Shifts in Demand and Supply for Goods and Services</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./3-3-changes-in-equilibrium-price-and-quantity-the-four-step-process.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">3.3 Changes in Equilibrium Price and Quantity: The Four-Step Process</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./3-4-price-ceilings-and-price-floors.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">3.4 Price Ceilings and Price Floors</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./3-5-demand-supply-and-efficiency.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">3.5 Demand, Supply, and Efficiency</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
 <span class="menu-text">4-Labor and Financial Markets</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./4-introduction-to-labor-and-financial-markets.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter Objectives</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./4-1-demand-and-supply-at-work-in-labor-markets.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">4.1 Demand and Supply at Work in Labor Markets</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./4-2-demand-and-supply-in-financial-markets.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">4.2 Demand and Supply in Financial Markets</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./4-3-the-market-system-as-an-efficient-mechanism-for-information.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">4.3 The Market System as an Efficient Mechanism for Information</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
 <span class="menu-text">5-Elasticity</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./5-introduction-to-elasticity.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter Objectives</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./5-1-price-elasticity-of-demand-and-price-elasticity-of-supply.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">5.1 Price Elasticity of Demand and Price Elasticity of Supply</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./5-2-polar-cases-of-elasticity-and-constant-elasticity.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">5.2 Polar Cases of Elasticity and Constant Elasticity</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./5-3-elasticity-and-pricing.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">5.3 Elasticity and Pricing</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./5-4-elasticity-in-areas-other-than-price.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">5.4 Elasticity in Areas Other Than Price</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">
 <span class="menu-text">6-Consumer Choices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./6-introduction-to-consumer-choices.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter Objectives</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./6-1-consumption-choices.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">6.1 Consumption Choices</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./6-2-how-changes-in-income-and-prices-affect-consumption-choices.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">6.2 How Changes in Income and Prices Affect Consumption Choices</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./6-3-behavioral-economics-an-alternative-framework-for-consumer-choice.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">6.3 Behavioral Economics: An Alternative Framework for Consumer Choice</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true">
 <span class="menu-text">7-Production, Costs, and Industry Structure</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./7-introduction-to-production-costs-and-industry-structure.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter Objectives</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./7-1-explicit-and-implicit-costs-and-accounting-and-economic-profit.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">7.1 Explicit and Implicit Costs, and Accounting and Economic Profit</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./7-2-production-in-the-short-run.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">7.2 Production in the Short Run</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./7-3-costs-in-the-short-run.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">7.3 Costs in the Short Run</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./7-4-production-in-the-long-run.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">7.4 Production in the Long Run</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./7-5-costs-in-the-long-run.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">7.5 Costs in the Long Run</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="true">
 <span class="menu-text">8-Perfect Competition</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./8-introduction-to-perfect-competition.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter Objectives</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./8-1-perfect-competition-and-why-it-matters.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">8.1 Perfect Competition and Why It Matters</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./8-2-how-perfectly-competitive-firms-make-output-decisions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">8.2 How Perfectly Competitive Firms Make Output Decisions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./8-3-entry-and-exit-decisions-in-the-long-run.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">8.3 Entry and Exit Decisions in the Long Run</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./8-4-efficiency-in-perfectly-competitive-markets.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">8.4 Efficiency in Perfectly Competitive Markets</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="true">
 <span class="menu-text">9-Monopoly</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./9-introduction-to-a-monopoly.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter Objectives</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./9-1-how-monopolies-form-barriers-to-entry.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">9.1 How Monopolies Form: Barriers to Entry</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./9-2-how-a-profit-maximizing-monopoly-chooses-output-and-price.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">9.2 How a Profit-Maximizing Monopoly Chooses Output and Price</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" aria-expanded="true">
 <span class="menu-text">10-Monopolistic Competition and Oligopoly</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-introduction-to-monopolistic-competition-and-oligopoly.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter Objectives</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-1-monopolistic-competition.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">10.1 Monopolistic Competition</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-2-oligopoly.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">10.2 Oligopoly</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" aria-expanded="true">
 <span class="menu-text">11-Monopoly and Antitrust Policy</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-introduction-to-monopoly-and-antitrust-policy.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter Objectives</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-1-corporate-mergers.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">11.1 Corporate Mergers</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-2-regulating-anticompetitive-behavior.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">11.2 Regulating Anticompetitive Behavior</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-3-regulating-natural-monopolies.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">11.3 Regulating Natural Monopolies</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-4-the-great-deregulation-experiment.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">11.4 The Great Deregulation Experiment</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" aria-expanded="true">
 <span class="menu-text">12-Environmental Protection and Negative Externalities</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-12" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-introduction-to-environmental-protection-and-negative-externalities.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter Objectives</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-1-the-economics-of-pollution.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">12.1 The Economics of Pollution</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-2-command-and-control-regulation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">12.2 Command-and-Control Regulation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-3-market-oriented-environmental-tools.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">12.3 Market-Oriented Environmental Tools</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-4-the-benefits-and-costs-of-u-s-environmental-laws.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">12.4 The Benefits and Costs of U.S. Environmental Laws</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-5-international-environmental-issues.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">12.5 International Environmental Issues</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-6-the-tradeoff-between-economic-output-and-environmental-protection.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">12.6 The Tradeoff between Economic Output and Environmental Protection</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" aria-expanded="true">
 <span class="menu-text">13-Positive Externalities and Public Goods</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-13" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-introduction-to-positive-externalities-and-public-goods.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter Objectives</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-1-investments-in-innovation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">13.1 Investments in Innovation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-2-how-governments-can-encourage-innovation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">13.2 How Governments Can Encourage Innovation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-3-public-goods.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">13.3 Public Goods</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" aria-expanded="true">
 <span class="menu-text">14-Labor Markets and Income</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-14" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-introduction-to-labor-markets-and-income.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter Objectives</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-1-the-theory-of-labor-markets.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">14.1 The Theory of Labor Markets</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-2-wages-and-employment-in-an-imperfectly-competitive-labor-market.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">14.2 Wages and Employment in an Imperfectly Competitive Labor Market</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-3-market-power-on-the-supply-side-of-labor-markets-unions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">14.3 Market Power on the Supply Side of Labor Markets: Unions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-4-bilateral-monopoly.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">14.4 Bilateral Monopoly</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-5-employment-discrimination.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">14.5 Employment Discrimination</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-6-immigration.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">14.6 Immigration</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-15" aria-expanded="true">
 <span class="menu-text">15-Poverty and Economic Inequality</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-15" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-15" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-introduction-to-poverty-and-economic-inequality.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter Objectives</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-1-drawing-the-poverty-line.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">15.1 Drawing the Poverty Line</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-2-the-poverty-trap.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">15.2 The Poverty Trap</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-3-the-safety-net.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">15.3 The Safety Net</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-4-income-inequality-measurement-and-causes.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">15.4 Income Inequality: Measurement and Causes</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-5-government-policies-to-reduce-income-inequality.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">15.5 Government Policies to Reduce Income Inequality</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-16" aria-expanded="true">
 <span class="menu-text">16-Information, Risk, and Insurance</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-16" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-16" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-introduction-to-information-risk-and-insurance.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter Objectives</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-1-the-problem-of-imperfect-information-and-asymmetric-information.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">16.1 The Problem of Imperfect Information and Asymmetric Information</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-2-insurance-and-imperfect-information.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">16.2 Insurance and Imperfect Information</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-17" aria-expanded="true">
 <span class="menu-text">17-Financial Markets</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-17" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-17" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17-introduction-to-financial-markets.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter Objectives</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17-1-how-businesses-raise-financial-capital.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">17.1 How Businesses Raise Financial Capital</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17-2-how-households-supply-financial-capital.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">17.2 How Households Supply Financial Capital</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17-3-how-to-accumulate-personal-wealth.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">17.3 How to Accumulate Personal Wealth</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-18" aria-expanded="true">
 <span class="menu-text">18-Public Economy</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-18" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-18" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./18-introduction-to-public-economy.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter Objectives</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./18-1-voter-participation-and-costs-of-elections.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">18.1 Voter Participation and Costs of Elections</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./18-2-special-interest-politics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">18.2 Special Interest Politics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./18-3-flaws-in-the-democratic-system-of-government.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">18.3 Flaws in the Democratic System of Government</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-19" aria-expanded="true">
 <span class="menu-text">19-International Trade</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-19" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-19" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./19-introduction-to-international-trade.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter Objectives</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./19-1-absolute-and-comparative-advantage.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">19.1 Absolute and Comparative Advantage</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./19-2-what-happens-when-a-country-has-an-absolute-advantage-in-all-goods.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">19.2 What Happens When a Country Has an Absolute Advantage in All Goods</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./19-3-intra-industry-trade-between-similar-economies.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">19.3 Intra-industry Trade between Similar Economies</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./19-4-the-benefits-of-reducing-barriers-to-international-trade.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">19.4 The Benefits of Reducing Barriers to International Trade</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-20" aria-expanded="true">
 <span class="menu-text">20-Globalization and Protectionism</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-20" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-20" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./20-introduction-to-globalization-and-protectionism.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter Objectives</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./20-1-protectionism-an-indirect-subsidy-from-consumers-to-producers.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">20.1 Protectionism: An Indirect Subsidy from Consumers to Producers</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./20-2-international-trade-and-its-effects-on-jobs-wages-and-working-conditions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">20.2 International Trade and Its Effects on Jobs, Wages, and Working Conditions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./20-3-arguments-in-support-of-restricting-imports.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">20.3 Arguments in Support of Restricting Imports</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./20-4-how-governments-enact-trade-policy-globally-regionally-and-nationally.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">20.4 How Governments Enact Trade Policy: Globally, Regionally, and Nationally</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./20-5-the-tradeoffs-of-trade-policy.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">20.5 The Tradeoffs of Trade Policy</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#learning-objectives" id="toc-learning-objectives" class="nav-link active" data-scroll-target="#learning-objectives">Learning Objectives</a></li>
  <li><a href="#demand-curves-perceived-by-a-perfectly-competitive-firm-and-by-a-monopoly" id="toc-demand-curves-perceived-by-a-perfectly-competitive-firm-and-by-a-monopoly" class="nav-link" data-scroll-target="#demand-curves-perceived-by-a-perfectly-competitive-firm-and-by-a-monopoly">Demand Curves Perceived by a Perfectly Competitive Firm and by a Monopoly</a></li>
  <li><a href="#clear-it-up" id="toc-clear-it-up" class="nav-link" data-scroll-target="#clear-it-up">Clear It Up</a></li>
  <li><a href="#clear-it-up-1" id="toc-clear-it-up-1" class="nav-link" data-scroll-target="#clear-it-up-1">Clear It Up</a></li>
  <li><a href="#total-cost-and-total-revenue-for-a-monopolist" id="toc-total-cost-and-total-revenue-for-a-monopolist" class="nav-link" data-scroll-target="#total-cost-and-total-revenue-for-a-monopolist">Total Cost and Total Revenue for a Monopolist</a></li>
  <li><a href="#marginal-revenue-and-marginal-cost-for-a-monopolist" id="toc-marginal-revenue-and-marginal-cost-for-a-monopolist" class="nav-link" data-scroll-target="#marginal-revenue-and-marginal-cost-for-a-monopolist">Marginal Revenue and Marginal Cost for a Monopolist</a></li>
  <li><a href="#work-it-out" id="toc-work-it-out" class="nav-link" data-scroll-target="#work-it-out">Work It Out</a></li>
  <li><a href="#illustrating-monopoly-profits" id="toc-illustrating-monopoly-profits" class="nav-link" data-scroll-target="#illustrating-monopoly-profits">Illustrating Monopoly Profits</a></li>
  <li><a href="#clear-it-up-2" id="toc-clear-it-up-2" class="nav-link" data-scroll-target="#clear-it-up-2">Clear It Up</a></li>
  <li><a href="#the-inefficiency-of-monopoly" id="toc-the-inefficiency-of-monopoly" class="nav-link" data-scroll-target="#the-inefficiency-of-monopoly">The Inefficiency of Monopoly</a></li>
  <li><a href="#bring-it-home" id="toc-bring-it-home" class="nav-link" data-scroll-target="#bring-it-home">Bring It Home</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">9.2 How a Profit-Maximizing Monopoly Chooses Output and Price</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="learning-objectives" class="level3">
<h3 class="anchored" data-anchor-id="learning-objectives">Learning Objectives</h3>
<p>By the end of this section, you will be able to:</p>
<ul>
<li>Explain the perceived demand curve for a perfect competitor and a monopoly</li>
<li>Analyze a demand curve for a monopoly and determine the output that maximizes profit and revenue</li>
<li>Calculate marginal revenue and marginal cost</li>
<li>Explain allocative efficiency as it pertains to the efficiency of a monopoly</li>
</ul>
<p>Consider a monopoly firm, comfortably surrounded by barriers to entry so that it need not fear competition from other producers. How will this monopoly choose its profit-maximizing quantity of output, and what price will it charge? Profits for the monopolist, like any firm, will be equal to total revenues minus total costs. We can analyze the pattern of costs for the monopoly within the same framework as the costs of a perfectly competitive firm—that is, by using total cost, fixed cost, variable cost, marginal cost, average cost, and average variable cost. However, because a monopoly faces no competition, its situation and its decision process will differ from that of a perfectly competitive firm. (The Clear It Up feature discusses how hard it is sometimes to define “market” in a monopoly situation.)</p>
</section>
<section id="demand-curves-perceived-by-a-perfectly-competitive-firm-and-by-a-monopoly" class="level3">
<h3 class="anchored" data-anchor-id="demand-curves-perceived-by-a-perfectly-competitive-firm-and-by-a-monopoly">Demand Curves Perceived by a Perfectly Competitive Firm and by a Monopoly</h3>
<p>A perfectly competitive firm acts as a price taker, so we calculate total revenue taking the given market price and multiplying it by the quantity of output that the firm chooses. The demand curve <em>as it is perceived by a perfectly competitive firm</em> appears in <a href="#CNX_Econ_C09_008">Figure 9.3</a> (a). The flat perceived demand curve means that, from the viewpoint of the perfectly competitive firm, it could sell either a relatively low quantity like Ql or a relatively high quantity like Qh at the market price P.</p>
<p><img src="media/9-2-how-a-profit-maximizing-monopoly-chooses-output-and-price_rId23.jpeg" style="width:6.5in;height:2.575in"></p>
<p>Figure 9.3 The Perceived Demand Curve for a Perfect Competitor and a Monopolist (a) A perfectly competitive firm perceives the demand curve that it faces to be flat. The flat shape means that the firm can sell either a low quantity (Ql) or a high quantity (Qh) at exactly the same price (P). (b) A monopolist perceives the demand curve that it faces to be the same as the market demand curve, which for most goods is downward-sloping. Thus, if the monopolist chooses a high level of output (Qh), it can charge only a relatively low price (PI). Conversely, if the monopolist chooses a low level of output (Ql), it can then charge a higher price (Ph). The challenge for the monopolist is to choose the combination of price and quantity that maximizes profits.</p>
</section>
<section id="clear-it-up" class="level3 Heading3Grey">
<h3 class="Heading3Grey anchored" data-anchor-id="clear-it-up">Clear It Up</h3>
<section id="what-defines-the-market" class="level4 Heading4Grey">
<h4 class="Heading4Grey anchored" data-anchor-id="what-defines-the-market">What defines the market?</h4>
<p>A monopoly is a firm that sells all or nearly all of the goods and services in a given market. However, what defines the “market”?</p>
<p>In a famous 1947 case, the federal government accused the DuPont company of having a monopoly in the cellophane market, pointing out that DuPont produced 75% of the cellophane in the United States. DuPont countered that even though it had a 75% market share in cellophane, it had less than a 20% share of the “flexible packaging materials,” which includes all other moisture-proof papers, films, and foils. In 1956, after years of legal appeals, the U.S. Supreme Court held that the broader market definition was more appropriate, and it dismissed the case against DuPont.</p>
<p>Questions over how to define the market continue today. True, Microsoft in the 1990s had a dominant share of the software for computer operating systems, but in the total market for all computer software and services, including everything from games to scientific programs, the Microsoft share was only about 14% in 2014. The Greyhound bus company may have a near-monopoly on the market for intercity bus transportation, but it is only a small share of the market for intercity transportation if that market includes private cars, airplanes, and railroad service. DeBeers has a monopoly in diamonds, but it is a much smaller share of the total market for precious gemstones and an even smaller share of the total market for jewelry. A small town in the country may have only one gas station: is this gas station a “monopoly,” or does it compete with gas stations that might be five, 10, or 50 miles away?</p>
<p>In general, if a firm produces a product without close substitutes, then we can consider the firm a monopoly producer in a single market. However, if buyers have a range of similar—even if not identical—options available from other firms, then the firm is not a monopoly. Still, arguments over whether substitutes are close or not close can be controversial.</p>
<p>While a monopolist can charge <em>any</em> price for its product, nonetheless the demand for the firm’s product constrains the price. No monopolist, even one that is thoroughly protected by high barriers to entry, can require consumers to purchase its product. Because the monopolist is the only firm in the market, its demand curve is the same as the market demand curve, which is, unlike that for a perfectly competitive firm, downward-sloping.</p>
<p><a href="#CNX_Econ_C09_008">Figure 9.3</a> illustrates this situation. The monopolist can either choose a point like R with a low price (Pl) and high quantity (Qh), or a point like S with a high price (Ph) and a low quantity (Ql), or some intermediate point. Setting the price too high will result in a low quantity sold, and will not bring in much revenue. Conversely, setting the price too low may result in a high quantity sold, but because of the low price, it will not bring in much revenue either. The challenge for the monopolist is to strike a profit-maximizing balance between the price it charges and the quantity that it sells. However, why isn’t the perfectly competitive firm’s demand curve also the market demand curve? See the following Clear It Up feature for the answer to this question.</p>
</section>
</section>
<section id="clear-it-up-1" class="level3 Heading3Grey">
<h3 class="Heading3Grey anchored" data-anchor-id="clear-it-up-1">Clear It Up</h3>
<section id="what-is-the-difference-between-perceived-demand-and-market-demand" class="level4 Heading4Grey">
<h4 class="Heading4Grey anchored" data-anchor-id="what-is-the-difference-between-perceived-demand-and-market-demand">What is the difference between perceived demand and market demand?</h4>
<p>The demand curve as perceived by a perfectly competitive firm is not the overall market demand curve for that product. However, the firm’s demand curve as perceived by a monopoly is the same as the market demand curve. The reason for the difference is that each perfectly competitive firm perceives the demand for its products in a market that includes many other firms. In effect, the demand curve perceived by a perfectly competitive firm is a tiny slice of the entire market demand curve. In contrast, a monopoly perceives demand for its product in a market where the monopoly is the only producer.</p>
</section>
</section>
<section id="total-cost-and-total-revenue-for-a-monopolist" class="level3">
<h3 class="anchored" data-anchor-id="total-cost-and-total-revenue-for-a-monopolist">Total Cost and Total Revenue for a Monopolist</h3>
<p>We can illustrate profits for a monopolist with a graph of total revenues and total costs, with the example of the hypothetical HealthPill firm in <a href="#CNX_Econ_C09_004">Figure 9.4</a>. The total cost curve has its typical shape that we learned about in <a href="http://openstax.org/books/principles-microeconomics-3e/pages/7-introduction-to-production-costs-and-industry-structure">Production, Costs and Industry Structure</a>, and that we used in <a href="http://openstax.org/books/principles-microeconomics-3e/pages/8-introduction-to-perfect-competition">Perfect Competition</a>; that is, total costs rise and the curve grows steeper as output increases, as the final column of <a href="#Table_09_02">Table 9.2</a> shows.</p>
<p><img src="media/9-2-how-a-profit-maximizing-monopoly-chooses-output-and-price_rId32.jpeg" style="width:4.88in;height:2.52in"></p>
<p>Figure 9.4 Total Revenue and Total Cost for the HealthPill Monopoly Total revenue for the monopoly firm called HealthPill first rises, then falls. Low levels of output bring in relatively little total revenue, because the quantity is low. High levels of output bring in relatively less revenue, because the high quantity pushes down the market price. The total cost curve is upward-sloping. Profits will be highest at the quantity of output where total revenue is most above total cost. The profit-maximizing level of output is not the same as the revenue-maximizing level of output, which should make sense, because profits take costs into account and revenues do not.</p>
<table class="table">
<colgroup>
<col style="width: 24%">
<col style="width: 24%">
<col style="width: 24%">
<col style="width: 24%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Quantity<br>
Q</th>
<th style="text-align: left;">Price<br>
P</th>
<th style="text-align: left;">Total Revenue<br>
TR</th>
<th style="text-align: left;">Total Cost<br>
TC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">1,200</td>
<td style="text-align: left;">1,200</td>
<td style="text-align: left;">500</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">1,100</td>
<td style="text-align: left;">2,200</td>
<td style="text-align: left;">750</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">1,000</td>
<td style="text-align: left;">3,000</td>
<td style="text-align: left;">1,000</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">900</td>
<td style="text-align: left;">3,600</td>
<td style="text-align: left;">1,250</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">800</td>
<td style="text-align: left;">4,000</td>
<td style="text-align: left;">1,650</td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: left;">700</td>
<td style="text-align: left;">4,200</td>
<td style="text-align: left;">2,500</td>
</tr>
<tr class="odd">
<td style="text-align: left;">7</td>
<td style="text-align: left;">600</td>
<td style="text-align: left;">4,200</td>
<td style="text-align: left;">4,000</td>
</tr>
<tr class="even">
<td style="text-align: left;">8</td>
<td style="text-align: left;">500</td>
<td style="text-align: left;">4,000</td>
<td style="text-align: left;">6,400</td>
</tr>
</tbody>
</table>
<p>Table 9.2 Total Costs and Total Revenues of HealthPill</p>
<p>Total revenue, though, is different. Since a monopolist faces a downward sloping demand curve, the only way it can sell more output is by reducing its price. Selling more output raises revenue, but lowering price reduces it. Thus, the shape of total revenue isn’t clear. Let’s explore this using the data in <a href="#Table_09_02">Table 9.2</a>, which shows quantities along the demand curve and the price at each quantity demanded, and then calculates total revenue by multiplying price times quantity at each level of output. (In this example, we give the output as 1, 2, 3, 4, and so on, for the sake of simplicity. If you prefer a dash of greater realism, you can imagine that the pharmaceutical company measures these output levels and the corresponding prices per 1,000 or 10,000 pills.) As the figure illustrates, total revenue for a monopolist has the shape of a hill, first rising, next flattening out, and then falling. In this example, total revenue is highest at a quantity of 6 or 7.</p>
<p>However, the monopolist is not seeking to maximize revenue, but instead to earn the highest possible profit. In the HealthPill example in <a href="#CNX_Econ_C09_004">Figure 9.4</a>, the highest profit will occur at the quantity where total revenue is the farthest above total cost. This looks to be somewhere in the middle of the graph, but where exactly? It is easier to see the profit maximizing level of output by using the marginal approach, to which we turn next.</p>
</section>
<section id="marginal-revenue-and-marginal-cost-for-a-monopolist" class="level3">
<h3 class="anchored" data-anchor-id="marginal-revenue-and-marginal-cost-for-a-monopolist">Marginal Revenue and Marginal Cost for a Monopolist</h3>
<p>In the real world, a monopolist often does not have enough information to analyze its entire total revenues or total costs curves. After all, the firm does not know exactly what would happen if it were to alter production dramatically. However, a monopolist often has fairly reliable information about how changing output by small or moderate amounts will affect its marginal revenues and marginal costs, because it has had experience with such changes over time and because modest changes are easier to extrapolate from current experience. A monopolist can use information on marginal revenue and marginal cost to seek out the profit-maximizing combination of quantity and price.</p>
<p><a href="#Table_09_03">Table 9.3</a> expands <a href="#Table_09_02">Table 9.2</a> using the figures on total costs and total revenues from the HealthPill example to calculate marginal revenue and marginal cost. This monopoly faces typical upward-sloping marginal cost and downward-sloping marginal revenue curves, as <a href="#CNX_Econ_C09_005">Figure 9.5</a> shows.</p>
<p>Notice that marginal revenue is zero at a quantity of 7, and turns negative at quantities higher than 7. It may seem counterintuitive that marginal revenue could ever be zero or negative: after all, doesn't an increase in quantity sold not always mean more revenue? For a perfect competitor, each additional unit sold brought a positive marginal revenue, because marginal revenue was equal to the given market price. However, a monopolist can sell a larger quantity and see a decline in total revenue. When a monopolist increases sales by one unit, it gains some marginal revenue from selling that extra unit, but also loses some marginal revenue because it must now sell every other unit at a lower price. As the quantity sold becomes higher, at some point the drop in price is proportionally more than the increase in greater quantity of sales, causing a situation where more sales bring in less revenue. In other words, marginal revenue is negative.</p>
<p><img src="media/9-2-how-a-profit-maximizing-monopoly-chooses-output-and-price_rId40.jpeg" style="width:4.88in;height:2.225in"></p>
<p>Figure 9.5 Marginal Revenue and Marginal Cost for the HealthPill Monopoly For a monopoly like HealthPill, marginal revenue decreases as it sells additional units of output. The marginal cost curve is upward-sloping. The profit-maximizing choice for the monopoly will be to produce at the quantity where marginal revenue is equal to marginal cost: that is, MR = MC. If the monopoly produces a lower quantity, then MR &gt; MC at those levels of output, and the firm can make higher profits by expanding output. If the firm produces at a greater quantity, then MC &gt; MR, and the firm can make higher profits by reducing its quantity of output.</p>
<table class="table">
<colgroup>
<col style="width: 20%">
<col style="width: 19%">
<col style="width: 19%">
<col style="width: 19%">
<col style="width: 19%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Quantity</strong><br>
<strong>Q</strong></th>
<th style="text-align: left;"><strong>Total Revenue</strong><br>
<strong>TR</strong></th>
<th style="text-align: left;"><strong>Marginal Revenue</strong><br>
<strong>MR</strong></th>
<th style="text-align: left;"><strong>Total Cost</strong><br>
<strong>TC</strong></th>
<th style="text-align: left;"><strong>Marginal Cost</strong><br>
<strong>MC</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">1,200</td>
<td style="text-align: left;">1,200</td>
<td style="text-align: left;">500</td>
<td style="text-align: left;">500</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">2,200</td>
<td style="text-align: left;">1,000</td>
<td style="text-align: left;">775</td>
<td style="text-align: left;">275</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">3,000</td>
<td style="text-align: left;">800</td>
<td style="text-align: left;">1,000</td>
<td style="text-align: left;">225</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">3,600</td>
<td style="text-align: left;">600</td>
<td style="text-align: left;">1,250</td>
<td style="text-align: left;">250</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">4,000</td>
<td style="text-align: left;">400</td>
<td style="text-align: left;">1,650</td>
<td style="text-align: left;">400</td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: left;">4,200</td>
<td style="text-align: left;">200</td>
<td style="text-align: left;">2,500</td>
<td style="text-align: left;">850</td>
</tr>
<tr class="odd">
<td style="text-align: left;">7</td>
<td style="text-align: left;">4,200</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">4,000</td>
<td style="text-align: left;">1,500</td>
</tr>
<tr class="even">
<td style="text-align: left;">8</td>
<td style="text-align: left;">4,000</td>
<td style="text-align: left;">–200</td>
<td style="text-align: left;">6,400</td>
<td style="text-align: left;">2,400</td>
</tr>
</tbody>
</table>
<p>Table 9.3 Costs and Revenues of HealthPill</p>
<p>A monopolist can determine its profit-maximizing price and quantity by analyzing the marginal revenue and marginal costs of producing an extra unit. If the marginal revenue exceeds the marginal cost, then the firm should produce the extra unit.</p>
<p>For example, at an output of 4 in <a href="#CNX_Econ_C09_005">Figure 9.5</a>, marginal revenue is 600 and marginal cost is 250, so producing this unit will clearly add to overall profits. At an output of 5, marginal revenue is 400 and marginal cost is 400, so producing this unit still means overall profits are unchanged. However, expanding output from 5 to 6 would involve a marginal revenue of 200 and a marginal cost of 850, so that sixth unit would actually reduce profits. Thus, the monopoly can tell from the marginal revenue and marginal cost that of the choices in the table, the profit-maximizing level of output is 5.</p>
<p>The monopoly could seek out the profit-maximizing level of output by increasing quantity by a small amount, calculating marginal revenue and marginal cost, and then either increasing output as long as marginal revenue exceeds marginal cost or reducing output if marginal cost exceeds marginal revenue. This process works without any need to calculate total revenue and total cost. Thus, a profit-maximizing monopoly should follow the rule of producing up to the quantity where marginal revenue is equal to marginal cost—that is, MR = MC. This quantity is easy to identify graphically, where MR and MC intersect.</p>
</section>
<section id="work-it-out" class="level3 Heading3Grey">
<h3 class="Heading3Grey anchored" data-anchor-id="work-it-out">Work It Out</h3>
<section id="maximizing-profits" class="level4 Heading4Grey">
<h4 class="Heading4Grey anchored" data-anchor-id="maximizing-profits">Maximizing Profits</h4>
<p>If you find it counterintuitive that producing where marginal revenue equals marginal cost will maximize profits, working through the numbers will help.</p>
<p>Step 1. Remember, we define marginal cost as the change in total cost from producing a small amount of additional output.</p>
<p><span class="math inline">\(\text{MC} = \frac{\text{change~in~total~cost}}{\text{change~in~quantity~produced}}\)</span></p>
<p>Step 2. Note that in <a href="#Table_09_03">Table 9.3</a>, as output increases from 1 to 2 units, total cost increases from $500 to $775. As a result, the marginal cost of the second unit will be:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="media/rId44.png" style="width:1.01042in;height:0.4375in" class="figure-img"></p>
<figcaption class="figure-caption">multiline equation row 1 MC equals dollar sign 775 en dash dollar sign 500 divided by one row 2 Blank equals dollar sign 275</figcaption>
</figure>
</div>
<p>Step 3. Remember that, similarly, marginal revenue is the change in total revenue from selling a small amount of additional output.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="media/rId46.png" style="width:1.63542in;height:0.23958in" class="figure-img"></p>
<figcaption class="figure-caption">multiline equation row 1 MR equals change in total revenue divided by change in quantity sold</figcaption>
</figure>
</div>
<p>Step 4. Note that in <a href="#Table_09_03">Table 9.3</a>, as output increases from 1 to 2 units, total revenue increases from $1200 to $2200. As a result, the marginal revenue of the second unit will be:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="media/rId48.png" style="width:1.125in;height:0.4375in" class="figure-img"></p>
<figcaption class="figure-caption">multiline equation row 1 MR equals dollar sign 2200 en dash dollar sign 1200 divided by one row 2 Blank equals dollar sign 1000</figcaption>
</figure>
</div>
<table class="table">
<colgroup>
<col style="width: 20%">
<col style="width: 19%">
<col style="width: 19%">
<col style="width: 19%">
<col style="width: 19%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Quantity</strong><br>
<strong>Q</strong></th>
<th style="text-align: left;"><strong>Marginal Revenue</strong><br>
<strong>MR</strong></th>
<th style="text-align: left;"><strong>Marginal Cost</strong><br>
<strong>MC</strong></th>
<th style="text-align: left;"><strong>Marginal Profit</strong><br>
<strong>MP</strong></th>
<th style="text-align: left;"><strong>Total Profit</strong><br>
<strong>P</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">1,200</td>
<td style="text-align: left;">500</td>
<td style="text-align: left;">700</td>
<td style="text-align: left;">700</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">1,000</td>
<td style="text-align: left;">275</td>
<td style="text-align: left;">725</td>
<td style="text-align: left;">1,425</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">800</td>
<td style="text-align: left;">225</td>
<td style="text-align: left;">575</td>
<td style="text-align: left;">2,000</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">600</td>
<td style="text-align: left;">250</td>
<td style="text-align: left;">350</td>
<td style="text-align: left;">2,350</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">400</td>
<td style="text-align: left;">400</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">2,350</td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: left;">200</td>
<td style="text-align: left;">850</td>
<td style="text-align: left;">−650</td>
<td style="text-align: left;">1,700</td>
</tr>
<tr class="odd">
<td style="text-align: left;">7</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">1,500</td>
<td style="text-align: left;">−1,500</td>
<td style="text-align: left;">200</td>
</tr>
<tr class="even">
<td style="text-align: left;">8</td>
<td style="text-align: left;">−200</td>
<td style="text-align: left;">2,400</td>
<td style="text-align: left;">−2,600</td>
<td style="text-align: left;">−2,400</td>
</tr>
</tbody>
</table>
<p>Table 9.4 Marginal Revenue, Marginal Cost, Marginal and Total Profit</p>
<p><a href="#Table_09_04">Table 9.4</a> repeats the marginal cost and marginal revenue data from <a href="#Table_09_03">Table 9.3</a>, and adds two more columns: Marginal profit is the profitability of each additional unit sold. We define it as marginal revenue minus marginal cost. Finally, total profit is the sum of marginal profits. As long as marginal profit is positive, producing more output will increase total profits. When marginal profit turns negative, producing more output will decrease total profits. Total profit is maximized where marginal revenue equals marginal cost. In this example, maximum profit occurs at 5 units of output.</p>
<p>A perfectly competitive firm will also find its profit-maximizing level of output where MR = MC. The key difference with a perfectly competitive firm is that in the case of perfect competition, marginal revenue is equal to price (MR = P), while for a monopolist, marginal revenue is not equal to the price, because changes in quantity of output affect the price.</p>
</section>
</section>
<section id="illustrating-monopoly-profits" class="level3">
<h3 class="anchored" data-anchor-id="illustrating-monopoly-profits">Illustrating Monopoly Profits</h3>
<p>It is straightforward to calculate profits of given numbers for total revenue and total cost. However, the size of monopoly profits can also be illustrated graphically with <a href="#CNX_Econ_C09_006">Figure 9.6</a>, which takes the marginal cost and marginal revenue curves from the previous exhibit and adds an average cost curve and the monopolist’s perceived demand curve. <a href="#eip-806">Table 9.5</a> shows the data for these curves.</p>
<table class="table">
<colgroup>
<col style="width: 20%">
<col style="width: 19%">
<col style="width: 19%">
<col style="width: 19%">
<col style="width: 19%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Quantity</strong><br>
<strong>Q</strong></th>
<th style="text-align: left;"><strong>Demand</strong><br>
<strong>P</strong></th>
<th style="text-align: left;"><strong>Marginal Revenue</strong><br>
<strong>MR</strong></th>
<th style="text-align: left;"><strong>Marginal Cost</strong><br>
<strong>MC</strong></th>
<th style="text-align: left;"><strong>Average Cost</strong><br>
<strong>AC</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">1,200</td>
<td style="text-align: left;">1,200</td>
<td style="text-align: left;">500</td>
<td style="text-align: left;">500</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">1,100</td>
<td style="text-align: left;">1,000</td>
<td style="text-align: left;">275</td>
<td style="text-align: left;">388</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">1,000</td>
<td style="text-align: left;">800</td>
<td style="text-align: left;">225</td>
<td style="text-align: left;">333</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">900</td>
<td style="text-align: left;">600</td>
<td style="text-align: left;">250</td>
<td style="text-align: left;">313</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">800</td>
<td style="text-align: left;">400</td>
<td style="text-align: left;">400</td>
<td style="text-align: left;">330</td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: left;">700</td>
<td style="text-align: left;">200</td>
<td style="text-align: left;">850</td>
<td style="text-align: left;">417</td>
</tr>
<tr class="odd">
<td style="text-align: left;">7</td>
<td style="text-align: left;">600</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">1,500</td>
<td style="text-align: left;">571</td>
</tr>
<tr class="even">
<td style="text-align: left;">8</td>
<td style="text-align: left;">500</td>
<td style="text-align: left;">–200</td>
<td style="text-align: left;">2,400</td>
<td style="text-align: left;">800</td>
</tr>
</tbody>
</table>
<p>Table 9.5</p>
<p><img src="media/9-2-how-a-profit-maximizing-monopoly-chooses-output-and-price_rId55.jpeg" style="width:4.88in;height:3.02in"></p>
<p>Figure 9.6 Illustrating Profits at the HealthPill Monopoly This figure begins with the same marginal revenue and marginal cost curves from the HealthPill monopoly from <a href="#CNX_Econ_C09_005">Figure 9.5</a>. It then adds an average cost curve and the demand curve that the monopolist faces. The HealthPill firm first chooses the quantity where MR = MC. In this example, the quantity is 5. The monopolist then decides what price to charge by looking at the demand curve it faces. The large box, with quantity on the horizontal axis and demand (which shows the price) on the vertical axis, shows total revenue for the firm. The lighter-shaded box, which is quantity on the horizontal axis and average cost of production on the vertical axis shows the firm's total costs. The large total revenue box minus the smaller total cost box leaves the darkly shaded box that shows total profits. Since the price charged is above average cost, the firm is earning positive profits.</p>
<p><a href="#CNX_Econ_C09_007">Figure 9.7</a> illustrates the three-step process where a monopolist: selects the profit-maximizing quantity to produce; decides what price to charge; determines total revenue, total cost, and profit.</p>
<p><strong>Step 1: The Monopolist Determines Its Profit-Maximizing Level of Output</strong></p>
<p>The firm can use the points on the demand curve D to calculate total revenue, and then, based on total revenue, calculate its marginal revenue curve. The profit-maximizing quantity will occur where MR = MC—or at the last possible point before marginal costs start exceeding marginal revenue. On <a href="#CNX_Econ_C09_006">Figure 9.6</a>, MR = MC occurs at an output of 5.</p>
<p><strong>Step 2: The Monopolist Decides What Price to Charge</strong></p>
<p>The monopolist will charge what the market is willing to pay. A dotted line drawn straight up from the profit-maximizing quantity to the demand curve shows the profit-maximizing price which, in <a href="#CNX_Econ_C09_006">Figure 9.6</a>, is $800. This price is above the average cost curve, which shows that the firm is earning profits.</p>
<p><strong>Step 3: Calculate Total Revenue, Total Cost, and Profit</strong></p>
<p>Total revenue is the overall shaded box, where the width of the box is the quantity sold and the height is the price. In <a href="#CNX_Econ_C09_006">Figure 9.6</a>, this is 5 x $800 = $4000. In <a href="#CNX_Econ_C09_006">Figure 9.6</a>, the bottom part of the shaded box, which is shaded more lightly, shows total costs; that is, quantity on the horizontal axis multiplied by average cost on the vertical axis or 5 x $330 = $1650. The larger box of total revenues minus the smaller box of total costs will equal profits, which the darkly shaded box shows. Using the numbers gives $4000 - $1650 = $2350. In a perfectly competitive market, the forces of entry would erode this profit in the long run. However, a monopolist is protected by barriers to entry. In fact, one obvious sign of a possible monopoly is when a firm earns profits year after year, while doing more or less the same thing, without ever seeing increased competition eroding those profits.</p>
<p><img src="media/9-2-how-a-profit-maximizing-monopoly-chooses-output-and-price_rId58.jpeg" style="width:4.145in;height:2.605in"></p>
<p>Figure 9.7 How a Profit-Maximizing Monopoly Decides Price In Step 1, the monopoly chooses the profit-maximizing level of output Q<sub>1</sub>, by choosing the quantity where MR = MC. In Step 2, the monopoly decides how much to charge for output level Q<sub>1</sub> by drawing a line straight up from Q<sub>1</sub> to point R on its perceived demand curve. Thus, the monopoly will charge a price (P<sub>1</sub>). In Step 3, the monopoly identifies its profit. Total revenue will be Q<sub>1</sub> multiplied by P<sub>1</sub>. Total cost will be Q<sub>1</sub> multiplied by the average cost of producing Q<sub>1</sub>, which point S shows on the average cost curve to be P<sub>2</sub>. Profits will be the total revenue rectangle minus the total cost rectangle, which the shaded zone in the figure shows.</p>
</section>
<section id="clear-it-up-2" class="level3 Heading3Grey">
<h3 class="Heading3Grey anchored" data-anchor-id="clear-it-up-2">Clear It Up</h3>
<section id="why-is-a-monopolists-marginal-revenue-always-less-than-the-price" class="level4 Heading4Grey">
<h4 class="Heading4Grey anchored" data-anchor-id="why-is-a-monopolists-marginal-revenue-always-less-than-the-price">Why is a monopolist’s marginal revenue always less than the price?</h4>
<p>The marginal revenue curve for a monopolist always lies beneath the market demand curve. To understand why, think about increasing the quantity along the demand curve by one unit, so that you take one step down the demand curve to a slightly higher quantity but a slightly lower price. A demand curve is not sequential: It is not that first we sell Q<sub>1</sub> at a higher price, and then we sell Q<sub>2</sub> at a lower price. Rather, a demand curve is conditional: If we charge the higher price, we would sell Q<sub>1</sub>. If, instead, we charge a lower price (on all the units that we sell), we would sell Q<sub>2</sub>.</p>
<p>When we think about increasing the quantity sold by one unit, marginal revenue is affected in two ways. First, we sell one additional unit at the new market price. Second, all the previous units, which we sold at the higher price, now sell for less. Because of the lower price on all units sold, the marginal revenue of selling a unit is less than the price of that unit—and the marginal revenue curve is below the demand curve. <em>Tip</em>: For a straight-line demand curve, MR and demand have the same vertical intercept. As output increases, marginal revenue decreases twice as fast as demand, so that the horizontal intercept of MR is halfway to the horizontal intercept of demand. You can see this in the <a href="#CNX_Econ_C09_009">Figure 9.8</a>.</p>
<p><img src="media/9-2-how-a-profit-maximizing-monopoly-chooses-output-and-price_rId61.jpeg" style="width:3.25in;height:2.365in"></p>
<p>Figure 9.8 The Monopolist’s Marginal Revenue Curve versus Demand Curve Because the market demand curve is conditional, the marginal revenue curve for a monopolist lies beneath the demand curve.</p>
</section>
</section>
<section id="the-inefficiency-of-monopoly" class="level3">
<h3 class="anchored" data-anchor-id="the-inefficiency-of-monopoly">The Inefficiency of Monopoly</h3>
<p>Most people criticize monopolies because they charge too high a price, but what economists object to is that monopolies do not supply enough output to be allocatively efficient. To understand why a monopoly is inefficient, it is useful to compare it with the benchmark model of perfect competition.</p>
<p>Allocative efficiency is an economic concept regarding efficiency at the social or societal level. It refers to producing the optimal quantity of some output, the quantity where the marginal benefit to society of one more unit just equals the marginal cost. The rule of profit maximization in a world of perfect competition was for each firm to produce the quantity of output where P = MC, where the price (P) is a measure of how much buyers value the good and the marginal cost (MC) is a measure of what marginal units cost society to produce. Following this rule assures allocative efficiency. If P &gt; MC, then the marginal benefit to society (as measured by P) is greater than the marginal cost to society of producing additional units, and a greater quantity should be produced. However, in the case of monopoly, price is always greater than marginal cost at the profit-maximizing level of output, as you can see by looking back at <a href="#CNX_Econ_C09_006">Figure 9.6</a>. Thus, consumers do not benefit from a monopoly because it will sell a lower quantity in the market, at a higher price, than would have been the case in a perfectly competitive market.</p>
<p>The problem of inefficiency for monopolies often runs even deeper than these issues, and also involves incentives for efficiency over longer periods of time. There are counterbalancing incentives here. On one side, firms may strive for new inventions and new intellectual property because they want to become monopolies and earn high profits—at least for a few years until the competition catches up. In this way, monopolies may come to exist because of competitive pressures on firms. However, once a barrier to entry is in place, a monopoly that does not need to fear competition can just produce the same old products in the same old way—while still ringing up a healthy rate of profit. John Hicks, who won the Nobel Prize for economics in 1972, wrote in 1935: “The best of all monopoly profits is a quiet life.” He did not mean the comment in a complimentary way. He meant that monopolies may bank their profits and slack off on trying to please their customers.</p>
<p>When AT&amp;T provided all of the local and long-distance phone service in the United States, along with manufacturing most of the phone equipment, the payment plans and types of phones did not change much. The old joke was that you could have any color phone you wanted, as long as it was black. However, in 1982, government litigation split up AT&amp;T into a number of local phone companies, a long-distance phone company, and a phone equipment manufacturer. An explosion of innovation followed. Services like call waiting, caller ID, three-way calling, voice mail through the phone company, mobile phones, and wireless connections to the internet all became available. Companies offered a wide range of payment plans, as well. It was no longer true that all phones were black. Instead, phones came in a wide variety of shapes and colors. The end of the telephone monopoly brought lower prices, a greater quantity of services, and also a wave of innovation aimed at attracting and pleasing customers.</p>
</section>
<section id="bring-it-home" class="level3 Heading3Grey">
<h3 class="Heading3Grey anchored" data-anchor-id="bring-it-home">Bring It Home</h3>
<section id="the-rest-is-history" class="level4 Heading4Grey">
<h4 class="Heading4Grey anchored" data-anchor-id="the-rest-is-history">The Rest is History</h4>
<p>In the opening case, we presented the East India Company and the Confederate States as a monopoly or near monopoly provider of a good. Nearly every American schoolchild knows the result of the “unwelcome visit” the “Mohawks” bestowed upon Boston Harbor’s tea-bearing ships—the Boston Tea Party. Regarding the cotton industry, we also know Great Britain remained neutral during the Civil War, taking neither side during the conflict.</p>
<p>Did the monopoly nature of these business have unintended and historical consequences? Might the American Revolution have been deterred, if the East India Company had sailed the tea-bearing ships back to England? Might the southern states have made different decisions had they not been so confident “King Cotton” would force diplomatic recognition of the Confederate States of America? Of course, it is not possible to definitively answer these questions. We cannot roll back the clock and try a different scenario. We can, however, consider the monopoly nature of these businesses and the roles they played and hypothesize about what might have occurred under different circumstances.</p>
<p>Perhaps if there had been legal free tea trade, the colonists would have seen things differently. There was smuggled Dutch tea in the colonial market. If the colonists had been able to freely purchase Dutch tea, they would have paid lower prices and avoided the tax.</p>
<p>What about the cotton monopoly? With one in five jobs in Great Britain depending on Southern cotton and the Confederate States as nearly the sole provider of that cotton, why did Great Britain remain neutral during the Civil War? At the beginning of the war, Britain simply drew down massive stores of cotton. These stockpiles lasted until near the end of 1862. Why did Britain not recognize the Confederacy at that point? Two reasons: The Emancipation Proclamation and new sources of cotton. Having outlawed slavery throughout the United Kingdom in 1833, it was politically impossible for Great Britain, empty cotton warehouses or not, to recognize, diplomatically, the Confederate States. In addition, during the two years it took to draw down the stockpiles, Britain expanded cotton imports from India, Egypt, and Brazil.</p>
<p>Monopoly sellers often see no threats to their superior marketplace position. In these examples did the power of the monopoly hide other possibilities from the decision makers? Perhaps. As a result of their actions, this is how history unfolded.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./9-1-how-monopolies-form-barriers-to-entry.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">9.1 How Monopolies Form: Barriers to Entry</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./10-introduction-to-monopolistic-competition-and-oligopoly.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-title">Chapter Objectives</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>